apiVersion: v1
kind: ConfigMap
metadata:
  name: server-go-configmap
data:
  config.yaml: |
    server:
      address:     ":7001"
      openapiPath: "/api.json"
      swaggerPath: "/swagger"

    logger:
      level : "all"
      stdout: true
