server:
  address: ":7001"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  graceful: true
  gracefulTimeout: 15

app:
  keys:
    - "SzNg8LgHjEUgTAc4"

database:
  default:
    link: "mysql:root:root@tcp(mysql:3306)/game_db_1?charset=utf8mb4&parseTime=true&loc=Local"
    debug: false

redis:
  default:
    address: "redis:6379"
    pass: "root"
    db: 0

logger:
  level: "info"
  stdout: true