# 本地容器环境配置（docker compose 内用）
server:
  address: ":7001"
  gracefulTimeout: 15

app:
  keys:
    - "SzNg8LgHjEUgTAc4"

database:
  default:
    link: "mysql:root:root@tcp(mysql:3306)/game_db_1?charset=utf8mb4&parseTime=true&loc=Local"
    debug: true
    slowThreshold: 300

redis:
  default:
    address: "redis:6379"
    pass: "root"
    db: 0

logger:
  level: "info"
  format: "console"
  stdout: true
  stdoutColorDisabled: false
