# 本地开发环境配置
server:
  address: ":7001"
  gracefulTimeout: 15

app:
  keys:
    - "SzNg8LgHjEUgTAc4"

database:
  default:
    link: "mysql:root:root@tcp(127.0.0.1:330)/game_db_1?charset=utf8mb4&parseTime=true&loc=Local"
    debug: true
    slowThreshold: 300

redis:
  default:
    address: "127.0.0.1:637"
    pass: "root"
    db: 0
    dialTimeoutMs: 3000
    readTimeoutMs: 500
    writeTimeoutMs: 500
    poolSize: 20
    minIdleConns: 2
    poolTimeoutMs: 1000

logger:
  level: "debug"
  format: "console"
  stdout: false
  clearOnStart: true
  outputPaths:
    - "log/app.log"
