server:
  address: ":7001"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  graceful: true
  gracefulTimeout: 15

app:
  keys:
    - "SzNg8LgHjEUgTAc4"

database:
  default:
    link: "mysql:root:root@tcp(127.0.0.1:330)/game_db_1?charset=utf8mb4&parseTime=true&loc=Local"
    debug: true

redis:
  default:
    address: "127.0.0.1:637"
    pass: "root"
    db: 0

logger:
  level: "info"
  stdout: true
  stdoutColorDisabled: false