// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package res

import (
	"server_go/api/res"
)

type ControllerV1 struct{}

func NewV1() res.IResV1 {
	return &ControllerV1{}
}
