// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package other

import (
	"server_go/api/other"
)

type ControllerV1 struct{}

func NewV1() other.IOtherV1 {
	return &ControllerV1{}
}
