gfcli:
  gen:
    dao:
      - link: "mysql:root:WZtest1@DB@tcp(172.10.1.15:3014)/huayuan?charset=utf8mb4&parseTime=true&loc=Local"
        descriptionTag: true
        noModelComment: true
        overwriteDao: true
        overwriteDo: true
        overwriteEntity: true
        tplDaoInternalPath: "./hack/tpl/dao_internal.tpl"