gfcli:
  gen:
    dao:
      - link: "mysql:root:root@tcp(127.0.0.1:330)/game_db_1?charset=utf8mb4&parseTime=true&loc=Local"
        descriptionTag: true
        noModelComment: true
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - ccr.ccs.tencentyun.com/justsoso-local
      - ccr.ccs.tencentyun.com/justsoso-test
      - ccr.ccs.tencentyun.com/justsoso-production