// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q              = new(Query)
	LogLogin       *logLogin
	LogMsg         *logMsg
	LogTrace       *logTrace
	MemConfig      *memConfig
	PrfFlower      *prfFlower
	PrfFlowerLevel *prfFlowerLevel
	PrfItem        *prfItem
	PrfRes         *prfRes
	PrfTask        *prfTask
	SysDie         *sysDie
	SysGm          *sysGm
	User           *user
	UserBag        *userBag
	UserBagTp      *userBagTp
	UserData       *userData
	UserItem       *userItem
	UserLoginkey   *userLoginkey
	UserOnline     *userOnline
	UserRes        *userRes
	UserTask       *userTask
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	LogLogin = &Q.LogLogin
	LogMsg = &Q.LogMsg
	LogTrace = &Q.LogTrace
	MemConfig = &Q.MemConfig
	PrfFlower = &Q.PrfFlower
	PrfFlowerLevel = &Q.PrfFlowerLevel
	PrfItem = &Q.PrfItem
	PrfRes = &Q.PrfRes
	PrfTask = &Q.PrfTask
	SysDie = &Q.SysDie
	SysGm = &Q.SysGm
	User = &Q.User
	UserBag = &Q.UserBag
	UserBagTp = &Q.UserBagTp
	UserData = &Q.UserData
	UserItem = &Q.UserItem
	UserLoginkey = &Q.UserLoginkey
	UserOnline = &Q.UserOnline
	UserRes = &Q.UserRes
	UserTask = &Q.UserTask
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:             db,
		LogLogin:       newLogLogin(db, opts...),
		LogMsg:         newLogMsg(db, opts...),
		LogTrace:       newLogTrace(db, opts...),
		MemConfig:      newMemConfig(db, opts...),
		PrfFlower:      newPrfFlower(db, opts...),
		PrfFlowerLevel: newPrfFlowerLevel(db, opts...),
		PrfItem:        newPrfItem(db, opts...),
		PrfRes:         newPrfRes(db, opts...),
		PrfTask:        newPrfTask(db, opts...),
		SysDie:         newSysDie(db, opts...),
		SysGm:          newSysGm(db, opts...),
		User:           newUser(db, opts...),
		UserBag:        newUserBag(db, opts...),
		UserBagTp:      newUserBagTp(db, opts...),
		UserData:       newUserData(db, opts...),
		UserItem:       newUserItem(db, opts...),
		UserLoginkey:   newUserLoginkey(db, opts...),
		UserOnline:     newUserOnline(db, opts...),
		UserRes:        newUserRes(db, opts...),
		UserTask:       newUserTask(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	LogLogin       logLogin
	LogMsg         logMsg
	LogTrace       logTrace
	MemConfig      memConfig
	PrfFlower      prfFlower
	PrfFlowerLevel prfFlowerLevel
	PrfItem        prfItem
	PrfRes         prfRes
	PrfTask        prfTask
	SysDie         sysDie
	SysGm          sysGm
	User           user
	UserBag        userBag
	UserBagTp      userBagTp
	UserData       userData
	UserItem       userItem
	UserLoginkey   userLoginkey
	UserOnline     userOnline
	UserRes        userRes
	UserTask       userTask
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		LogLogin:       q.LogLogin.clone(db),
		LogMsg:         q.LogMsg.clone(db),
		LogTrace:       q.LogTrace.clone(db),
		MemConfig:      q.MemConfig.clone(db),
		PrfFlower:      q.PrfFlower.clone(db),
		PrfFlowerLevel: q.PrfFlowerLevel.clone(db),
		PrfItem:        q.PrfItem.clone(db),
		PrfRes:         q.PrfRes.clone(db),
		PrfTask:        q.PrfTask.clone(db),
		SysDie:         q.SysDie.clone(db),
		SysGm:          q.SysGm.clone(db),
		User:           q.User.clone(db),
		UserBag:        q.UserBag.clone(db),
		UserBagTp:      q.UserBagTp.clone(db),
		UserData:       q.UserData.clone(db),
		UserItem:       q.UserItem.clone(db),
		UserLoginkey:   q.UserLoginkey.clone(db),
		UserOnline:     q.UserOnline.clone(db),
		UserRes:        q.UserRes.clone(db),
		UserTask:       q.UserTask.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		LogLogin:       q.LogLogin.replaceDB(db),
		LogMsg:         q.LogMsg.replaceDB(db),
		LogTrace:       q.LogTrace.replaceDB(db),
		MemConfig:      q.MemConfig.replaceDB(db),
		PrfFlower:      q.PrfFlower.replaceDB(db),
		PrfFlowerLevel: q.PrfFlowerLevel.replaceDB(db),
		PrfItem:        q.PrfItem.replaceDB(db),
		PrfRes:         q.PrfRes.replaceDB(db),
		PrfTask:        q.PrfTask.replaceDB(db),
		SysDie:         q.SysDie.replaceDB(db),
		SysGm:          q.SysGm.replaceDB(db),
		User:           q.User.replaceDB(db),
		UserBag:        q.UserBag.replaceDB(db),
		UserBagTp:      q.UserBagTp.replaceDB(db),
		UserData:       q.UserData.replaceDB(db),
		UserItem:       q.UserItem.replaceDB(db),
		UserLoginkey:   q.UserLoginkey.replaceDB(db),
		UserOnline:     q.UserOnline.replaceDB(db),
		UserRes:        q.UserRes.replaceDB(db),
		UserTask:       q.UserTask.replaceDB(db),
	}
}

type queryCtx struct {
	LogLogin       ILogLoginDo
	LogMsg         ILogMsgDo
	LogTrace       ILogTraceDo
	MemConfig      IMemConfigDo
	PrfFlower      IPrfFlowerDo
	PrfFlowerLevel IPrfFlowerLevelDo
	PrfItem        IPrfItemDo
	PrfRes         IPrfResDo
	PrfTask        IPrfTaskDo
	SysDie         ISysDieDo
	SysGm          ISysGmDo
	User           IUserDo
	UserBag        IUserBagDo
	UserBagTp      IUserBagTpDo
	UserData       IUserDataDo
	UserItem       IUserItemDo
	UserLoginkey   IUserLoginkeyDo
	UserOnline     IUserOnlineDo
	UserRes        IUserResDo
	UserTask       IUserTaskDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		LogLogin:       q.LogLogin.WithContext(ctx),
		LogMsg:         q.LogMsg.WithContext(ctx),
		LogTrace:       q.LogTrace.WithContext(ctx),
		MemConfig:      q.MemConfig.WithContext(ctx),
		PrfFlower:      q.PrfFlower.WithContext(ctx),
		PrfFlowerLevel: q.PrfFlowerLevel.WithContext(ctx),
		PrfItem:        q.PrfItem.WithContext(ctx),
		PrfRes:         q.PrfRes.WithContext(ctx),
		PrfTask:        q.PrfTask.WithContext(ctx),
		SysDie:         q.SysDie.WithContext(ctx),
		SysGm:          q.SysGm.WithContext(ctx),
		User:           q.User.WithContext(ctx),
		UserBag:        q.UserBag.WithContext(ctx),
		UserBagTp:      q.UserBagTp.WithContext(ctx),
		UserData:       q.UserData.WithContext(ctx),
		UserItem:       q.UserItem.WithContext(ctx),
		UserLoginkey:   q.UserLoginkey.WithContext(ctx),
		UserOnline:     q.UserOnline.WithContext(ctx),
		UserRes:        q.UserRes.WithContext(ctx),
		UserTask:       q.UserTask.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
