// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"server_go/dao/model"
)

func newLogTrace(db *gorm.DB, opts ...gen.DOOption) logTrace {
	_logTrace := logTrace{}

	_logTrace.logTraceDo.UseDB(db, opts...)
	_logTrace.logTraceDo.UseModel(&model.LogTrace{})

	tableName := _logTrace.logTraceDo.TableName()
	_logTrace.ALL = field.NewAsterisk(tableName)
	_logTrace.ID = field.NewInt64(tableName, "id")
	_logTrace.UID = field.NewInt32(tableName, "uid")
	_logTrace.Type = field.NewString(tableName, "type")
	_logTrace.Num = field.NewInt32(tableName, "num")
	_logTrace.Before = field.NewInt32(tableName, "before")
	_logTrace.After = field.NewInt32(tableName, "after")
	_logTrace.Reason = field.NewString(tableName, "reason")
	_logTrace.RequestID = field.NewString(tableName, "request_id")
	_logTrace.Time = field.NewTime(tableName, "time")

	_logTrace.fillFieldMap()

	return _logTrace
}

// logTrace 记录各种货币的获得及使用情况.
type logTrace struct {
	logTraceDo

	ALL       field.Asterisk
	ID        field.Int64
	UID       field.Int32
	Type      field.String
	Num       field.Int32
	Before    field.Int32
	After     field.Int32
	Reason    field.String
	RequestID field.String
	Time      field.Time

	fieldMap map[string]field.Expr
}

func (l logTrace) Table(newTableName string) *logTrace {
	l.logTraceDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l logTrace) As(alias string) *logTrace {
	l.logTraceDo.DO = *(l.logTraceDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *logTrace) updateTableName(table string) *logTrace {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewInt64(table, "id")
	l.UID = field.NewInt32(table, "uid")
	l.Type = field.NewString(table, "type")
	l.Num = field.NewInt32(table, "num")
	l.Before = field.NewInt32(table, "before")
	l.After = field.NewInt32(table, "after")
	l.Reason = field.NewString(table, "reason")
	l.RequestID = field.NewString(table, "request_id")
	l.Time = field.NewTime(table, "time")

	l.fillFieldMap()

	return l
}

func (l *logTrace) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *logTrace) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 9)
	l.fieldMap["id"] = l.ID
	l.fieldMap["uid"] = l.UID
	l.fieldMap["type"] = l.Type
	l.fieldMap["num"] = l.Num
	l.fieldMap["before"] = l.Before
	l.fieldMap["after"] = l.After
	l.fieldMap["reason"] = l.Reason
	l.fieldMap["request_id"] = l.RequestID
	l.fieldMap["time"] = l.Time
}

func (l logTrace) clone(db *gorm.DB) logTrace {
	l.logTraceDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l logTrace) replaceDB(db *gorm.DB) logTrace {
	l.logTraceDo.ReplaceDB(db)
	return l
}

type logTraceDo struct{ gen.DO }

type ILogTraceDo interface {
	gen.SubQuery
	Debug() ILogTraceDo
	WithContext(ctx context.Context) ILogTraceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILogTraceDo
	WriteDB() ILogTraceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILogTraceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILogTraceDo
	Not(conds ...gen.Condition) ILogTraceDo
	Or(conds ...gen.Condition) ILogTraceDo
	Select(conds ...field.Expr) ILogTraceDo
	Where(conds ...gen.Condition) ILogTraceDo
	Order(conds ...field.Expr) ILogTraceDo
	Distinct(cols ...field.Expr) ILogTraceDo
	Omit(cols ...field.Expr) ILogTraceDo
	Join(table schema.Tabler, on ...field.Expr) ILogTraceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILogTraceDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILogTraceDo
	Group(cols ...field.Expr) ILogTraceDo
	Having(conds ...gen.Condition) ILogTraceDo
	Limit(limit int) ILogTraceDo
	Offset(offset int) ILogTraceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILogTraceDo
	Unscoped() ILogTraceDo
	Create(values ...*model.LogTrace) error
	CreateInBatches(values []*model.LogTrace, batchSize int) error
	Save(values ...*model.LogTrace) error
	First() (*model.LogTrace, error)
	Take() (*model.LogTrace, error)
	Last() (*model.LogTrace, error)
	Find() ([]*model.LogTrace, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LogTrace, err error)
	FindInBatches(result *[]*model.LogTrace, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.LogTrace) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILogTraceDo
	Assign(attrs ...field.AssignExpr) ILogTraceDo
	Joins(fields ...field.RelationField) ILogTraceDo
	Preload(fields ...field.RelationField) ILogTraceDo
	FirstOrInit() (*model.LogTrace, error)
	FirstOrCreate() (*model.LogTrace, error)
	FindByPage(offset int, limit int) (result []*model.LogTrace, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILogTraceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l logTraceDo) Debug() ILogTraceDo {
	return l.withDO(l.DO.Debug())
}

func (l logTraceDo) WithContext(ctx context.Context) ILogTraceDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l logTraceDo) ReadDB() ILogTraceDo {
	return l.Clauses(dbresolver.Read)
}

func (l logTraceDo) WriteDB() ILogTraceDo {
	return l.Clauses(dbresolver.Write)
}

func (l logTraceDo) Session(config *gorm.Session) ILogTraceDo {
	return l.withDO(l.DO.Session(config))
}

func (l logTraceDo) Clauses(conds ...clause.Expression) ILogTraceDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l logTraceDo) Returning(value interface{}, columns ...string) ILogTraceDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l logTraceDo) Not(conds ...gen.Condition) ILogTraceDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l logTraceDo) Or(conds ...gen.Condition) ILogTraceDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l logTraceDo) Select(conds ...field.Expr) ILogTraceDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l logTraceDo) Where(conds ...gen.Condition) ILogTraceDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l logTraceDo) Order(conds ...field.Expr) ILogTraceDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l logTraceDo) Distinct(cols ...field.Expr) ILogTraceDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l logTraceDo) Omit(cols ...field.Expr) ILogTraceDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l logTraceDo) Join(table schema.Tabler, on ...field.Expr) ILogTraceDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l logTraceDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILogTraceDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l logTraceDo) RightJoin(table schema.Tabler, on ...field.Expr) ILogTraceDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l logTraceDo) Group(cols ...field.Expr) ILogTraceDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l logTraceDo) Having(conds ...gen.Condition) ILogTraceDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l logTraceDo) Limit(limit int) ILogTraceDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l logTraceDo) Offset(offset int) ILogTraceDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l logTraceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILogTraceDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l logTraceDo) Unscoped() ILogTraceDo {
	return l.withDO(l.DO.Unscoped())
}

func (l logTraceDo) Create(values ...*model.LogTrace) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l logTraceDo) CreateInBatches(values []*model.LogTrace, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l logTraceDo) Save(values ...*model.LogTrace) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l logTraceDo) First() (*model.LogTrace, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LogTrace), nil
	}
}

func (l logTraceDo) Take() (*model.LogTrace, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LogTrace), nil
	}
}

func (l logTraceDo) Last() (*model.LogTrace, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LogTrace), nil
	}
}

func (l logTraceDo) Find() ([]*model.LogTrace, error) {
	result, err := l.DO.Find()
	return result.([]*model.LogTrace), err
}

func (l logTraceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LogTrace, err error) {
	buf := make([]*model.LogTrace, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l logTraceDo) FindInBatches(result *[]*model.LogTrace, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l logTraceDo) Attrs(attrs ...field.AssignExpr) ILogTraceDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l logTraceDo) Assign(attrs ...field.AssignExpr) ILogTraceDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l logTraceDo) Joins(fields ...field.RelationField) ILogTraceDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l logTraceDo) Preload(fields ...field.RelationField) ILogTraceDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l logTraceDo) FirstOrInit() (*model.LogTrace, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LogTrace), nil
	}
}

func (l logTraceDo) FirstOrCreate() (*model.LogTrace, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LogTrace), nil
	}
}

func (l logTraceDo) FindByPage(offset int, limit int) (result []*model.LogTrace, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l logTraceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l logTraceDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l logTraceDo) Delete(models ...*model.LogTrace) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *logTraceDo) withDO(do gen.Dao) *logTraceDo {
	l.DO = *do.(*gen.DO)
	return l
}
