// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"server_go/dao/model"
)

func newLogMsg(db *gorm.DB, opts ...gen.DOOption) logMsg {
	_logMsg := logMsg{}

	_logMsg.logMsgDo.UseDB(db, opts...)
	_logMsg.logMsgDo.UseModel(&model.LogMsg{})

	tableName := _logMsg.logMsgDo.TableName()
	_logMsg.ALL = field.NewAsterisk(tableName)
	_logMsg.ID = field.NewInt32(tableName, "id")
	_logMsg.UID = field.NewInt32(tableName, "uid")
	_logMsg.Msg = field.NewString(tableName, "msg")
	_logMsg.RequestID = field.NewString(tableName, "request_id")
	_logMsg.Time = field.NewTime(tableName, "time")

	_logMsg.fillFieldMap()

	return _logMsg
}

type logMsg struct {
	logMsgDo

	ALL       field.Asterisk
	ID        field.Int32
	UID       field.Int32
	Msg       field.String
	RequestID field.String
	Time      field.Time

	fieldMap map[string]field.Expr
}

func (l logMsg) Table(newTableName string) *logMsg {
	l.logMsgDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l logMsg) As(alias string) *logMsg {
	l.logMsgDo.DO = *(l.logMsgDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *logMsg) updateTableName(table string) *logMsg {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewInt32(table, "id")
	l.UID = field.NewInt32(table, "uid")
	l.Msg = field.NewString(table, "msg")
	l.RequestID = field.NewString(table, "request_id")
	l.Time = field.NewTime(table, "time")

	l.fillFieldMap()

	return l
}

func (l *logMsg) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *logMsg) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 5)
	l.fieldMap["id"] = l.ID
	l.fieldMap["uid"] = l.UID
	l.fieldMap["msg"] = l.Msg
	l.fieldMap["request_id"] = l.RequestID
	l.fieldMap["time"] = l.Time
}

func (l logMsg) clone(db *gorm.DB) logMsg {
	l.logMsgDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l logMsg) replaceDB(db *gorm.DB) logMsg {
	l.logMsgDo.ReplaceDB(db)
	return l
}

type logMsgDo struct{ gen.DO }

type ILogMsgDo interface {
	gen.SubQuery
	Debug() ILogMsgDo
	WithContext(ctx context.Context) ILogMsgDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILogMsgDo
	WriteDB() ILogMsgDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILogMsgDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILogMsgDo
	Not(conds ...gen.Condition) ILogMsgDo
	Or(conds ...gen.Condition) ILogMsgDo
	Select(conds ...field.Expr) ILogMsgDo
	Where(conds ...gen.Condition) ILogMsgDo
	Order(conds ...field.Expr) ILogMsgDo
	Distinct(cols ...field.Expr) ILogMsgDo
	Omit(cols ...field.Expr) ILogMsgDo
	Join(table schema.Tabler, on ...field.Expr) ILogMsgDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILogMsgDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILogMsgDo
	Group(cols ...field.Expr) ILogMsgDo
	Having(conds ...gen.Condition) ILogMsgDo
	Limit(limit int) ILogMsgDo
	Offset(offset int) ILogMsgDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILogMsgDo
	Unscoped() ILogMsgDo
	Create(values ...*model.LogMsg) error
	CreateInBatches(values []*model.LogMsg, batchSize int) error
	Save(values ...*model.LogMsg) error
	First() (*model.LogMsg, error)
	Take() (*model.LogMsg, error)
	Last() (*model.LogMsg, error)
	Find() ([]*model.LogMsg, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LogMsg, err error)
	FindInBatches(result *[]*model.LogMsg, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.LogMsg) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILogMsgDo
	Assign(attrs ...field.AssignExpr) ILogMsgDo
	Joins(fields ...field.RelationField) ILogMsgDo
	Preload(fields ...field.RelationField) ILogMsgDo
	FirstOrInit() (*model.LogMsg, error)
	FirstOrCreate() (*model.LogMsg, error)
	FindByPage(offset int, limit int) (result []*model.LogMsg, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILogMsgDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l logMsgDo) Debug() ILogMsgDo {
	return l.withDO(l.DO.Debug())
}

func (l logMsgDo) WithContext(ctx context.Context) ILogMsgDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l logMsgDo) ReadDB() ILogMsgDo {
	return l.Clauses(dbresolver.Read)
}

func (l logMsgDo) WriteDB() ILogMsgDo {
	return l.Clauses(dbresolver.Write)
}

func (l logMsgDo) Session(config *gorm.Session) ILogMsgDo {
	return l.withDO(l.DO.Session(config))
}

func (l logMsgDo) Clauses(conds ...clause.Expression) ILogMsgDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l logMsgDo) Returning(value interface{}, columns ...string) ILogMsgDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l logMsgDo) Not(conds ...gen.Condition) ILogMsgDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l logMsgDo) Or(conds ...gen.Condition) ILogMsgDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l logMsgDo) Select(conds ...field.Expr) ILogMsgDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l logMsgDo) Where(conds ...gen.Condition) ILogMsgDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l logMsgDo) Order(conds ...field.Expr) ILogMsgDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l logMsgDo) Distinct(cols ...field.Expr) ILogMsgDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l logMsgDo) Omit(cols ...field.Expr) ILogMsgDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l logMsgDo) Join(table schema.Tabler, on ...field.Expr) ILogMsgDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l logMsgDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILogMsgDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l logMsgDo) RightJoin(table schema.Tabler, on ...field.Expr) ILogMsgDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l logMsgDo) Group(cols ...field.Expr) ILogMsgDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l logMsgDo) Having(conds ...gen.Condition) ILogMsgDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l logMsgDo) Limit(limit int) ILogMsgDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l logMsgDo) Offset(offset int) ILogMsgDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l logMsgDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILogMsgDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l logMsgDo) Unscoped() ILogMsgDo {
	return l.withDO(l.DO.Unscoped())
}

func (l logMsgDo) Create(values ...*model.LogMsg) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l logMsgDo) CreateInBatches(values []*model.LogMsg, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l logMsgDo) Save(values ...*model.LogMsg) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l logMsgDo) First() (*model.LogMsg, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LogMsg), nil
	}
}

func (l logMsgDo) Take() (*model.LogMsg, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LogMsg), nil
	}
}

func (l logMsgDo) Last() (*model.LogMsg, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LogMsg), nil
	}
}

func (l logMsgDo) Find() ([]*model.LogMsg, error) {
	result, err := l.DO.Find()
	return result.([]*model.LogMsg), err
}

func (l logMsgDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LogMsg, err error) {
	buf := make([]*model.LogMsg, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l logMsgDo) FindInBatches(result *[]*model.LogMsg, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l logMsgDo) Attrs(attrs ...field.AssignExpr) ILogMsgDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l logMsgDo) Assign(attrs ...field.AssignExpr) ILogMsgDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l logMsgDo) Joins(fields ...field.RelationField) ILogMsgDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l logMsgDo) Preload(fields ...field.RelationField) ILogMsgDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l logMsgDo) FirstOrInit() (*model.LogMsg, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LogMsg), nil
	}
}

func (l logMsgDo) FirstOrCreate() (*model.LogMsg, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LogMsg), nil
	}
}

func (l logMsgDo) FindByPage(offset int, limit int) (result []*model.LogMsg, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l logMsgDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l logMsgDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l logMsgDo) Delete(models ...*model.LogMsg) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *logMsgDo) withDO(do gen.Dao) *logMsgDo {
	l.DO = *do.(*gen.DO)
	return l
}
