// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"server_go/dao/model"
)

func newMemConfig(db *gorm.DB, opts ...gen.DOOption) memConfig {
	_memConfig := memConfig{}

	_memConfig.memConfigDo.UseDB(db, opts...)
	_memConfig.memConfigDo.UseModel(&model.MemConfig{})

	tableName := _memConfig.memConfigDo.TableName()
	_memConfig.ALL = field.NewAsterisk(tableName)
	_memConfig.ID = field.NewInt32(tableName, "id")
	_memConfig.Value = field.NewString(tableName, "value")
	_memConfig.Tips = field.NewString(tableName, "tips")

	_memConfig.fillFieldMap()

	return _memConfig
}

type memConfig struct {
	memConfigDo

	ALL   field.Asterisk
	ID    field.Int32
	Value field.String
	Tips  field.String

	fieldMap map[string]field.Expr
}

func (m memConfig) Table(newTableName string) *memConfig {
	m.memConfigDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m memConfig) As(alias string) *memConfig {
	m.memConfigDo.DO = *(m.memConfigDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *memConfig) updateTableName(table string) *memConfig {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt32(table, "id")
	m.Value = field.NewString(table, "value")
	m.Tips = field.NewString(table, "tips")

	m.fillFieldMap()

	return m
}

func (m *memConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *memConfig) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 3)
	m.fieldMap["id"] = m.ID
	m.fieldMap["value"] = m.Value
	m.fieldMap["tips"] = m.Tips
}

func (m memConfig) clone(db *gorm.DB) memConfig {
	m.memConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m memConfig) replaceDB(db *gorm.DB) memConfig {
	m.memConfigDo.ReplaceDB(db)
	return m
}

type memConfigDo struct{ gen.DO }

type IMemConfigDo interface {
	gen.SubQuery
	Debug() IMemConfigDo
	WithContext(ctx context.Context) IMemConfigDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMemConfigDo
	WriteDB() IMemConfigDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMemConfigDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMemConfigDo
	Not(conds ...gen.Condition) IMemConfigDo
	Or(conds ...gen.Condition) IMemConfigDo
	Select(conds ...field.Expr) IMemConfigDo
	Where(conds ...gen.Condition) IMemConfigDo
	Order(conds ...field.Expr) IMemConfigDo
	Distinct(cols ...field.Expr) IMemConfigDo
	Omit(cols ...field.Expr) IMemConfigDo
	Join(table schema.Tabler, on ...field.Expr) IMemConfigDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMemConfigDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMemConfigDo
	Group(cols ...field.Expr) IMemConfigDo
	Having(conds ...gen.Condition) IMemConfigDo
	Limit(limit int) IMemConfigDo
	Offset(offset int) IMemConfigDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMemConfigDo
	Unscoped() IMemConfigDo
	Create(values ...*model.MemConfig) error
	CreateInBatches(values []*model.MemConfig, batchSize int) error
	Save(values ...*model.MemConfig) error
	First() (*model.MemConfig, error)
	Take() (*model.MemConfig, error)
	Last() (*model.MemConfig, error)
	Find() ([]*model.MemConfig, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MemConfig, err error)
	FindInBatches(result *[]*model.MemConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MemConfig) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMemConfigDo
	Assign(attrs ...field.AssignExpr) IMemConfigDo
	Joins(fields ...field.RelationField) IMemConfigDo
	Preload(fields ...field.RelationField) IMemConfigDo
	FirstOrInit() (*model.MemConfig, error)
	FirstOrCreate() (*model.MemConfig, error)
	FindByPage(offset int, limit int) (result []*model.MemConfig, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMemConfigDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m memConfigDo) Debug() IMemConfigDo {
	return m.withDO(m.DO.Debug())
}

func (m memConfigDo) WithContext(ctx context.Context) IMemConfigDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m memConfigDo) ReadDB() IMemConfigDo {
	return m.Clauses(dbresolver.Read)
}

func (m memConfigDo) WriteDB() IMemConfigDo {
	return m.Clauses(dbresolver.Write)
}

func (m memConfigDo) Session(config *gorm.Session) IMemConfigDo {
	return m.withDO(m.DO.Session(config))
}

func (m memConfigDo) Clauses(conds ...clause.Expression) IMemConfigDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m memConfigDo) Returning(value interface{}, columns ...string) IMemConfigDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m memConfigDo) Not(conds ...gen.Condition) IMemConfigDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m memConfigDo) Or(conds ...gen.Condition) IMemConfigDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m memConfigDo) Select(conds ...field.Expr) IMemConfigDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m memConfigDo) Where(conds ...gen.Condition) IMemConfigDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m memConfigDo) Order(conds ...field.Expr) IMemConfigDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m memConfigDo) Distinct(cols ...field.Expr) IMemConfigDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m memConfigDo) Omit(cols ...field.Expr) IMemConfigDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m memConfigDo) Join(table schema.Tabler, on ...field.Expr) IMemConfigDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m memConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMemConfigDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m memConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) IMemConfigDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m memConfigDo) Group(cols ...field.Expr) IMemConfigDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m memConfigDo) Having(conds ...gen.Condition) IMemConfigDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m memConfigDo) Limit(limit int) IMemConfigDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m memConfigDo) Offset(offset int) IMemConfigDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m memConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMemConfigDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m memConfigDo) Unscoped() IMemConfigDo {
	return m.withDO(m.DO.Unscoped())
}

func (m memConfigDo) Create(values ...*model.MemConfig) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m memConfigDo) CreateInBatches(values []*model.MemConfig, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m memConfigDo) Save(values ...*model.MemConfig) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m memConfigDo) First() (*model.MemConfig, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemConfig), nil
	}
}

func (m memConfigDo) Take() (*model.MemConfig, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemConfig), nil
	}
}

func (m memConfigDo) Last() (*model.MemConfig, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemConfig), nil
	}
}

func (m memConfigDo) Find() ([]*model.MemConfig, error) {
	result, err := m.DO.Find()
	return result.([]*model.MemConfig), err
}

func (m memConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MemConfig, err error) {
	buf := make([]*model.MemConfig, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m memConfigDo) FindInBatches(result *[]*model.MemConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m memConfigDo) Attrs(attrs ...field.AssignExpr) IMemConfigDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m memConfigDo) Assign(attrs ...field.AssignExpr) IMemConfigDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m memConfigDo) Joins(fields ...field.RelationField) IMemConfigDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m memConfigDo) Preload(fields ...field.RelationField) IMemConfigDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m memConfigDo) FirstOrInit() (*model.MemConfig, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemConfig), nil
	}
}

func (m memConfigDo) FirstOrCreate() (*model.MemConfig, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemConfig), nil
	}
}

func (m memConfigDo) FindByPage(offset int, limit int) (result []*model.MemConfig, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m memConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m memConfigDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m memConfigDo) Delete(models ...*model.MemConfig) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *memConfigDo) withDO(do gen.Dao) *memConfigDo {
	m.DO = *do.(*gen.DO)
	return m
}
