// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"server_go/dao/model"
)

func newPrfItem(db *gorm.DB, opts ...gen.DOOption) prfItem {
	_prfItem := prfItem{}

	_prfItem.prfItemDo.UseDB(db, opts...)
	_prfItem.prfItemDo.UseModel(&model.PrfItem{})

	tableName := _prfItem.prfItemDo.TableName()
	_prfItem.ALL = field.NewAsterisk(tableName)
	_prfItem.ID = field.NewInt32(tableName, "id")
	_prfItem.Ser = field.NewInt32(tableName, "ser")
	_prfItem.Type = field.NewInt32(tableName, "type")
	_prfItem.Cost = field.NewInt32(tableName, "cost")
	_prfItem.Lv = field.NewInt32(tableName, "lv")
	_prfItem.From = field.NewString(tableName, "from")
	_prfItem.Name = field.NewString(tableName, "name")
	_prfItem.Tips = field.NewString(tableName, "tips")
	_prfItem.Star = field.NewInt32(tableName, "star")
	_prfItem.Next = field.NewInt32(tableName, "next")
	_prfItem.AutoDrop = field.NewInt32(tableName, "auto_drop")
	_prfItem.NeedOpen = field.NewInt32(tableName, "need_open")
	_prfItem.CoolDrop = field.NewInt32(tableName, "cool_drop")
	_prfItem.CoolTime = field.NewInt32(tableName, "cool_time")
	_prfItem.CoolMaxnum = field.NewInt32(tableName, "cool_maxnum")
	_prfItem.CoolMoney = field.NewInt32(tableName, "cool_money")
	_prfItem.Sell = field.NewInt32(tableName, "sell")
	_prfItem.Use = field.NewInt32(tableName, "use")
	_prfItem.Die = field.NewInt32(tableName, "die")
	_prfItem.Exp = field.NewInt32(tableName, "exp")
	_prfItem.Gold = field.NewInt32(tableName, "gold")
	_prfItem.Rare = field.NewInt32(tableName, "rare")
	_prfItem.Tids = field.NewString(tableName, "tids")
	_prfItem.Count_ = field.NewString(tableName, "count")

	_prfItem.fillFieldMap()

	return _prfItem
}

type prfItem struct {
	prfItemDo

	ALL field.Asterisk
	ID  field.Int32
	Ser field.Int32 // 道具系列
	/*
		道具类型
		0 普通道具
		1 工厂道具
		2 转换器
		3 点击使用的道具
		4 拖拽到目标使用的道具
	*/
	Type       field.Int32
	Cost       field.Int32  // 工厂类型道具产出消耗的体力
	Lv         field.Int32  // 道具等级
	From       field.String // 来源id
	Name       field.String // 道具名称
	Tips       field.String // 道具介绍
	Star       field.Int32  // 该道具对应的绿星数量
	Next       field.Int32  // 合成道具id
	AutoDrop   field.Int32  // 工厂是否自动产出道具
	NeedOpen   field.Int32  // 是否需要等待开启
	CoolDrop   field.Int32  // 一次CD掉落个数
	CoolTime   field.Int32  // 冷却时间
	CoolMaxnum field.Int32  // 冷却时间累积次数
	CoolMoney  field.Int32  // 冷却加速花费钻石（最大值）
	Sell       field.Int32  // 出售价格-金币
	Use        field.Int32  // 可直接使用的道具，boxid
	/*
		特殊-掉落完后变成什么
		<0 直接消失
		==0 进入cd
		>0 变成指定道具, 如果道具不存在也消失
	*/
	Die    field.Int32
	Exp    field.Int32  // 该等级道具合成下一级道具时是否会产出经验
	Gold   field.Int32  // 副本合成掉落金币
	Rare   field.Int32  // 0=普通，1=稀有（出售时跳出提醒框）
	Tids   field.String // 转换器内可投入物品的id
	Count_ field.String // 转换器内对应投入物品的数量

	fieldMap map[string]field.Expr
}

func (p prfItem) Table(newTableName string) *prfItem {
	p.prfItemDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p prfItem) As(alias string) *prfItem {
	p.prfItemDo.DO = *(p.prfItemDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *prfItem) updateTableName(table string) *prfItem {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt32(table, "id")
	p.Ser = field.NewInt32(table, "ser")
	p.Type = field.NewInt32(table, "type")
	p.Cost = field.NewInt32(table, "cost")
	p.Lv = field.NewInt32(table, "lv")
	p.From = field.NewString(table, "from")
	p.Name = field.NewString(table, "name")
	p.Tips = field.NewString(table, "tips")
	p.Star = field.NewInt32(table, "star")
	p.Next = field.NewInt32(table, "next")
	p.AutoDrop = field.NewInt32(table, "auto_drop")
	p.NeedOpen = field.NewInt32(table, "need_open")
	p.CoolDrop = field.NewInt32(table, "cool_drop")
	p.CoolTime = field.NewInt32(table, "cool_time")
	p.CoolMaxnum = field.NewInt32(table, "cool_maxnum")
	p.CoolMoney = field.NewInt32(table, "cool_money")
	p.Sell = field.NewInt32(table, "sell")
	p.Use = field.NewInt32(table, "use")
	p.Die = field.NewInt32(table, "die")
	p.Exp = field.NewInt32(table, "exp")
	p.Gold = field.NewInt32(table, "gold")
	p.Rare = field.NewInt32(table, "rare")
	p.Tids = field.NewString(table, "tids")
	p.Count_ = field.NewString(table, "count")

	p.fillFieldMap()

	return p
}

func (p *prfItem) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *prfItem) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 24)
	p.fieldMap["id"] = p.ID
	p.fieldMap["ser"] = p.Ser
	p.fieldMap["type"] = p.Type
	p.fieldMap["cost"] = p.Cost
	p.fieldMap["lv"] = p.Lv
	p.fieldMap["from"] = p.From
	p.fieldMap["name"] = p.Name
	p.fieldMap["tips"] = p.Tips
	p.fieldMap["star"] = p.Star
	p.fieldMap["next"] = p.Next
	p.fieldMap["auto_drop"] = p.AutoDrop
	p.fieldMap["need_open"] = p.NeedOpen
	p.fieldMap["cool_drop"] = p.CoolDrop
	p.fieldMap["cool_time"] = p.CoolTime
	p.fieldMap["cool_maxnum"] = p.CoolMaxnum
	p.fieldMap["cool_money"] = p.CoolMoney
	p.fieldMap["sell"] = p.Sell
	p.fieldMap["use"] = p.Use
	p.fieldMap["die"] = p.Die
	p.fieldMap["exp"] = p.Exp
	p.fieldMap["gold"] = p.Gold
	p.fieldMap["rare"] = p.Rare
	p.fieldMap["tids"] = p.Tids
	p.fieldMap["count"] = p.Count_
}

func (p prfItem) clone(db *gorm.DB) prfItem {
	p.prfItemDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p prfItem) replaceDB(db *gorm.DB) prfItem {
	p.prfItemDo.ReplaceDB(db)
	return p
}

type prfItemDo struct{ gen.DO }

type IPrfItemDo interface {
	gen.SubQuery
	Debug() IPrfItemDo
	WithContext(ctx context.Context) IPrfItemDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPrfItemDo
	WriteDB() IPrfItemDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPrfItemDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPrfItemDo
	Not(conds ...gen.Condition) IPrfItemDo
	Or(conds ...gen.Condition) IPrfItemDo
	Select(conds ...field.Expr) IPrfItemDo
	Where(conds ...gen.Condition) IPrfItemDo
	Order(conds ...field.Expr) IPrfItemDo
	Distinct(cols ...field.Expr) IPrfItemDo
	Omit(cols ...field.Expr) IPrfItemDo
	Join(table schema.Tabler, on ...field.Expr) IPrfItemDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPrfItemDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPrfItemDo
	Group(cols ...field.Expr) IPrfItemDo
	Having(conds ...gen.Condition) IPrfItemDo
	Limit(limit int) IPrfItemDo
	Offset(offset int) IPrfItemDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPrfItemDo
	Unscoped() IPrfItemDo
	Create(values ...*model.PrfItem) error
	CreateInBatches(values []*model.PrfItem, batchSize int) error
	Save(values ...*model.PrfItem) error
	First() (*model.PrfItem, error)
	Take() (*model.PrfItem, error)
	Last() (*model.PrfItem, error)
	Find() ([]*model.PrfItem, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PrfItem, err error)
	FindInBatches(result *[]*model.PrfItem, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PrfItem) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPrfItemDo
	Assign(attrs ...field.AssignExpr) IPrfItemDo
	Joins(fields ...field.RelationField) IPrfItemDo
	Preload(fields ...field.RelationField) IPrfItemDo
	FirstOrInit() (*model.PrfItem, error)
	FirstOrCreate() (*model.PrfItem, error)
	FindByPage(offset int, limit int) (result []*model.PrfItem, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPrfItemDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p prfItemDo) Debug() IPrfItemDo {
	return p.withDO(p.DO.Debug())
}

func (p prfItemDo) WithContext(ctx context.Context) IPrfItemDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p prfItemDo) ReadDB() IPrfItemDo {
	return p.Clauses(dbresolver.Read)
}

func (p prfItemDo) WriteDB() IPrfItemDo {
	return p.Clauses(dbresolver.Write)
}

func (p prfItemDo) Session(config *gorm.Session) IPrfItemDo {
	return p.withDO(p.DO.Session(config))
}

func (p prfItemDo) Clauses(conds ...clause.Expression) IPrfItemDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p prfItemDo) Returning(value interface{}, columns ...string) IPrfItemDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p prfItemDo) Not(conds ...gen.Condition) IPrfItemDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p prfItemDo) Or(conds ...gen.Condition) IPrfItemDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p prfItemDo) Select(conds ...field.Expr) IPrfItemDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p prfItemDo) Where(conds ...gen.Condition) IPrfItemDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p prfItemDo) Order(conds ...field.Expr) IPrfItemDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p prfItemDo) Distinct(cols ...field.Expr) IPrfItemDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p prfItemDo) Omit(cols ...field.Expr) IPrfItemDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p prfItemDo) Join(table schema.Tabler, on ...field.Expr) IPrfItemDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p prfItemDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPrfItemDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p prfItemDo) RightJoin(table schema.Tabler, on ...field.Expr) IPrfItemDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p prfItemDo) Group(cols ...field.Expr) IPrfItemDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p prfItemDo) Having(conds ...gen.Condition) IPrfItemDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p prfItemDo) Limit(limit int) IPrfItemDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p prfItemDo) Offset(offset int) IPrfItemDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p prfItemDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPrfItemDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p prfItemDo) Unscoped() IPrfItemDo {
	return p.withDO(p.DO.Unscoped())
}

func (p prfItemDo) Create(values ...*model.PrfItem) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p prfItemDo) CreateInBatches(values []*model.PrfItem, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p prfItemDo) Save(values ...*model.PrfItem) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p prfItemDo) First() (*model.PrfItem, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrfItem), nil
	}
}

func (p prfItemDo) Take() (*model.PrfItem, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrfItem), nil
	}
}

func (p prfItemDo) Last() (*model.PrfItem, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrfItem), nil
	}
}

func (p prfItemDo) Find() ([]*model.PrfItem, error) {
	result, err := p.DO.Find()
	return result.([]*model.PrfItem), err
}

func (p prfItemDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PrfItem, err error) {
	buf := make([]*model.PrfItem, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p prfItemDo) FindInBatches(result *[]*model.PrfItem, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p prfItemDo) Attrs(attrs ...field.AssignExpr) IPrfItemDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p prfItemDo) Assign(attrs ...field.AssignExpr) IPrfItemDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p prfItemDo) Joins(fields ...field.RelationField) IPrfItemDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p prfItemDo) Preload(fields ...field.RelationField) IPrfItemDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p prfItemDo) FirstOrInit() (*model.PrfItem, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrfItem), nil
	}
}

func (p prfItemDo) FirstOrCreate() (*model.PrfItem, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrfItem), nil
	}
}

func (p prfItemDo) FindByPage(offset int, limit int) (result []*model.PrfItem, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p prfItemDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p prfItemDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p prfItemDo) Delete(models ...*model.PrfItem) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *prfItemDo) withDO(do gen.Dao) *prfItemDo {
	p.DO = *do.(*gen.DO)
	return p
}
