// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"server_go/dao/model"
)

func newPrfRes(db *gorm.DB, opts ...gen.DOOption) prfRes {
	_prfRes := prfRes{}

	_prfRes.prfResDo.UseDB(db, opts...)
	_prfRes.prfResDo.UseModel(&model.PrfRes{})

	tableName := _prfRes.prfResDo.TableName()
	_prfRes.ALL = field.NewAsterisk(tableName)
	_prfRes.ID = field.NewInt32(tableName, "id")
	_prfRes.Name = field.NewString(tableName, "name")
	_prfRes.Tips = field.NewString(tableName, "tips")

	_prfRes.fillFieldMap()

	return _prfRes
}

// prfRes 游戏资源定义汇总
type prfRes struct {
	prfResDo

	ALL  field.Asterisk
	ID   field.Int32  // 资源ID
	Name field.String // 资源名称
	Tips field.String // 资源说明,用法提示

	fieldMap map[string]field.Expr
}

func (p prfRes) Table(newTableName string) *prfRes {
	p.prfResDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p prfRes) As(alias string) *prfRes {
	p.prfResDo.DO = *(p.prfResDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *prfRes) updateTableName(table string) *prfRes {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt32(table, "id")
	p.Name = field.NewString(table, "name")
	p.Tips = field.NewString(table, "tips")

	p.fillFieldMap()

	return p
}

func (p *prfRes) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *prfRes) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 3)
	p.fieldMap["id"] = p.ID
	p.fieldMap["name"] = p.Name
	p.fieldMap["tips"] = p.Tips
}

func (p prfRes) clone(db *gorm.DB) prfRes {
	p.prfResDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p prfRes) replaceDB(db *gorm.DB) prfRes {
	p.prfResDo.ReplaceDB(db)
	return p
}

type prfResDo struct{ gen.DO }

type IPrfResDo interface {
	gen.SubQuery
	Debug() IPrfResDo
	WithContext(ctx context.Context) IPrfResDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPrfResDo
	WriteDB() IPrfResDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPrfResDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPrfResDo
	Not(conds ...gen.Condition) IPrfResDo
	Or(conds ...gen.Condition) IPrfResDo
	Select(conds ...field.Expr) IPrfResDo
	Where(conds ...gen.Condition) IPrfResDo
	Order(conds ...field.Expr) IPrfResDo
	Distinct(cols ...field.Expr) IPrfResDo
	Omit(cols ...field.Expr) IPrfResDo
	Join(table schema.Tabler, on ...field.Expr) IPrfResDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPrfResDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPrfResDo
	Group(cols ...field.Expr) IPrfResDo
	Having(conds ...gen.Condition) IPrfResDo
	Limit(limit int) IPrfResDo
	Offset(offset int) IPrfResDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPrfResDo
	Unscoped() IPrfResDo
	Create(values ...*model.PrfRes) error
	CreateInBatches(values []*model.PrfRes, batchSize int) error
	Save(values ...*model.PrfRes) error
	First() (*model.PrfRes, error)
	Take() (*model.PrfRes, error)
	Last() (*model.PrfRes, error)
	Find() ([]*model.PrfRes, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PrfRes, err error)
	FindInBatches(result *[]*model.PrfRes, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PrfRes) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPrfResDo
	Assign(attrs ...field.AssignExpr) IPrfResDo
	Joins(fields ...field.RelationField) IPrfResDo
	Preload(fields ...field.RelationField) IPrfResDo
	FirstOrInit() (*model.PrfRes, error)
	FirstOrCreate() (*model.PrfRes, error)
	FindByPage(offset int, limit int) (result []*model.PrfRes, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPrfResDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p prfResDo) Debug() IPrfResDo {
	return p.withDO(p.DO.Debug())
}

func (p prfResDo) WithContext(ctx context.Context) IPrfResDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p prfResDo) ReadDB() IPrfResDo {
	return p.Clauses(dbresolver.Read)
}

func (p prfResDo) WriteDB() IPrfResDo {
	return p.Clauses(dbresolver.Write)
}

func (p prfResDo) Session(config *gorm.Session) IPrfResDo {
	return p.withDO(p.DO.Session(config))
}

func (p prfResDo) Clauses(conds ...clause.Expression) IPrfResDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p prfResDo) Returning(value interface{}, columns ...string) IPrfResDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p prfResDo) Not(conds ...gen.Condition) IPrfResDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p prfResDo) Or(conds ...gen.Condition) IPrfResDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p prfResDo) Select(conds ...field.Expr) IPrfResDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p prfResDo) Where(conds ...gen.Condition) IPrfResDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p prfResDo) Order(conds ...field.Expr) IPrfResDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p prfResDo) Distinct(cols ...field.Expr) IPrfResDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p prfResDo) Omit(cols ...field.Expr) IPrfResDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p prfResDo) Join(table schema.Tabler, on ...field.Expr) IPrfResDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p prfResDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPrfResDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p prfResDo) RightJoin(table schema.Tabler, on ...field.Expr) IPrfResDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p prfResDo) Group(cols ...field.Expr) IPrfResDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p prfResDo) Having(conds ...gen.Condition) IPrfResDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p prfResDo) Limit(limit int) IPrfResDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p prfResDo) Offset(offset int) IPrfResDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p prfResDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPrfResDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p prfResDo) Unscoped() IPrfResDo {
	return p.withDO(p.DO.Unscoped())
}

func (p prfResDo) Create(values ...*model.PrfRes) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p prfResDo) CreateInBatches(values []*model.PrfRes, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p prfResDo) Save(values ...*model.PrfRes) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p prfResDo) First() (*model.PrfRes, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrfRes), nil
	}
}

func (p prfResDo) Take() (*model.PrfRes, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrfRes), nil
	}
}

func (p prfResDo) Last() (*model.PrfRes, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrfRes), nil
	}
}

func (p prfResDo) Find() ([]*model.PrfRes, error) {
	result, err := p.DO.Find()
	return result.([]*model.PrfRes), err
}

func (p prfResDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PrfRes, err error) {
	buf := make([]*model.PrfRes, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p prfResDo) FindInBatches(result *[]*model.PrfRes, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p prfResDo) Attrs(attrs ...field.AssignExpr) IPrfResDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p prfResDo) Assign(attrs ...field.AssignExpr) IPrfResDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p prfResDo) Joins(fields ...field.RelationField) IPrfResDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p prfResDo) Preload(fields ...field.RelationField) IPrfResDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p prfResDo) FirstOrInit() (*model.PrfRes, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrfRes), nil
	}
}

func (p prfResDo) FirstOrCreate() (*model.PrfRes, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrfRes), nil
	}
}

func (p prfResDo) FindByPage(offset int, limit int) (result []*model.PrfRes, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p prfResDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p prfResDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p prfResDo) Delete(models ...*model.PrfRes) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *prfResDo) withDO(do gen.Dao) *prfResDo {
	p.DO = *do.(*gen.DO)
	return p
}
