// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"server_gin/dao/model"
)

func newPrfFlowerLevel(db *gorm.DB, opts ...gen.DOOption) prfFlowerLevel {
	_prfFlowerLevel := prfFlowerLevel{}

	_prfFlowerLevel.prfFlowerLevelDo.UseDB(db, opts...)
	_prfFlowerLevel.prfFlowerLevelDo.UseModel(&model.PrfFlowerLevel{})

	tableName := _prfFlowerLevel.prfFlowerLevelDo.TableName()
	_prfFlowerLevel.ALL = field.NewAsterisk(tableName)
	_prfFlowerLevel.ID = field.NewInt32(tableName, "id")
	_prfFlowerLevel.Flower = field.NewInt32(tableName, "flower")
	_prfFlowerLevel.Level = field.NewInt32(tableName, "level")
	_prfFlowerLevel.SeedUp = field.NewInt32(tableName, "seed_up")
	_prfFlowerLevel.CoinUp = field.NewInt32(tableName, "coin_up")
	_prfFlowerLevel.ReapExp = field.NewInt32(tableName, "reap_exp")
	_prfFlowerLevel.ReapRound = field.NewInt32(tableName, "reap_round")
	_prfFlowerLevel.ReapInterval = field.NewInt32(tableName, "reap_interval")
	_prfFlowerLevel.SeedDrop = field.NewInt32(tableName, "seed_drop")
	_prfFlowerLevel.SeedDropRate = field.NewString(tableName, "seed_drop_rate")
	_prfFlowerLevel.ReapCnt = field.NewInt32(tableName, "reap_cnt")
	_prfFlowerLevel.FlowerMin = field.NewInt32(tableName, "flower_min")

	_prfFlowerLevel.fillFieldMap()

	return _prfFlowerLevel
}

type prfFlowerLevel struct {
	prfFlowerLevelDo

	ALL          field.Asterisk
	ID           field.Int32
	Flower       field.Int32  // 花id
	Level        field.Int32  // 花-等级
	SeedUp       field.Int32  // 升到下级需要的种子，最大等级填-1
	CoinUp       field.Int32  // 升到下级需要的金币，最大等级填-1
	ReapExp      field.Int32  // 收割经验
	ReapRound    field.Int32  // 收获次数
	ReapInterval field.Int32  // 收获间隔
	SeedDrop     field.Int32  // 种子掉落数量
	SeedDropRate field.String // 种子掉落概率，填100代表1%概率
	ReapCnt      field.Int32  // 一次收获几个
	FlowerMin    field.Int32  // 摘花保底数量

	fieldMap map[string]field.Expr
}

func (p prfFlowerLevel) Table(newTableName string) *prfFlowerLevel {
	p.prfFlowerLevelDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p prfFlowerLevel) As(alias string) *prfFlowerLevel {
	p.prfFlowerLevelDo.DO = *(p.prfFlowerLevelDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *prfFlowerLevel) updateTableName(table string) *prfFlowerLevel {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt32(table, "id")
	p.Flower = field.NewInt32(table, "flower")
	p.Level = field.NewInt32(table, "level")
	p.SeedUp = field.NewInt32(table, "seed_up")
	p.CoinUp = field.NewInt32(table, "coin_up")
	p.ReapExp = field.NewInt32(table, "reap_exp")
	p.ReapRound = field.NewInt32(table, "reap_round")
	p.ReapInterval = field.NewInt32(table, "reap_interval")
	p.SeedDrop = field.NewInt32(table, "seed_drop")
	p.SeedDropRate = field.NewString(table, "seed_drop_rate")
	p.ReapCnt = field.NewInt32(table, "reap_cnt")
	p.FlowerMin = field.NewInt32(table, "flower_min")

	p.fillFieldMap()

	return p
}

func (p *prfFlowerLevel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *prfFlowerLevel) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 12)
	p.fieldMap["id"] = p.ID
	p.fieldMap["flower"] = p.Flower
	p.fieldMap["level"] = p.Level
	p.fieldMap["seed_up"] = p.SeedUp
	p.fieldMap["coin_up"] = p.CoinUp
	p.fieldMap["reap_exp"] = p.ReapExp
	p.fieldMap["reap_round"] = p.ReapRound
	p.fieldMap["reap_interval"] = p.ReapInterval
	p.fieldMap["seed_drop"] = p.SeedDrop
	p.fieldMap["seed_drop_rate"] = p.SeedDropRate
	p.fieldMap["reap_cnt"] = p.ReapCnt
	p.fieldMap["flower_min"] = p.FlowerMin
}

func (p prfFlowerLevel) clone(db *gorm.DB) prfFlowerLevel {
	p.prfFlowerLevelDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p prfFlowerLevel) replaceDB(db *gorm.DB) prfFlowerLevel {
	p.prfFlowerLevelDo.ReplaceDB(db)
	return p
}

type prfFlowerLevelDo struct{ gen.DO }

type IPrfFlowerLevelDo interface {
	gen.SubQuery
	Debug() IPrfFlowerLevelDo
	WithContext(ctx context.Context) IPrfFlowerLevelDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPrfFlowerLevelDo
	WriteDB() IPrfFlowerLevelDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPrfFlowerLevelDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPrfFlowerLevelDo
	Not(conds ...gen.Condition) IPrfFlowerLevelDo
	Or(conds ...gen.Condition) IPrfFlowerLevelDo
	Select(conds ...field.Expr) IPrfFlowerLevelDo
	Where(conds ...gen.Condition) IPrfFlowerLevelDo
	Order(conds ...field.Expr) IPrfFlowerLevelDo
	Distinct(cols ...field.Expr) IPrfFlowerLevelDo
	Omit(cols ...field.Expr) IPrfFlowerLevelDo
	Join(table schema.Tabler, on ...field.Expr) IPrfFlowerLevelDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPrfFlowerLevelDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPrfFlowerLevelDo
	Group(cols ...field.Expr) IPrfFlowerLevelDo
	Having(conds ...gen.Condition) IPrfFlowerLevelDo
	Limit(limit int) IPrfFlowerLevelDo
	Offset(offset int) IPrfFlowerLevelDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPrfFlowerLevelDo
	Unscoped() IPrfFlowerLevelDo
	Create(values ...*model.PrfFlowerLevel) error
	CreateInBatches(values []*model.PrfFlowerLevel, batchSize int) error
	Save(values ...*model.PrfFlowerLevel) error
	First() (*model.PrfFlowerLevel, error)
	Take() (*model.PrfFlowerLevel, error)
	Last() (*model.PrfFlowerLevel, error)
	Find() ([]*model.PrfFlowerLevel, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PrfFlowerLevel, err error)
	FindInBatches(result *[]*model.PrfFlowerLevel, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PrfFlowerLevel) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPrfFlowerLevelDo
	Assign(attrs ...field.AssignExpr) IPrfFlowerLevelDo
	Joins(fields ...field.RelationField) IPrfFlowerLevelDo
	Preload(fields ...field.RelationField) IPrfFlowerLevelDo
	FirstOrInit() (*model.PrfFlowerLevel, error)
	FirstOrCreate() (*model.PrfFlowerLevel, error)
	FindByPage(offset int, limit int) (result []*model.PrfFlowerLevel, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPrfFlowerLevelDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p prfFlowerLevelDo) Debug() IPrfFlowerLevelDo {
	return p.withDO(p.DO.Debug())
}

func (p prfFlowerLevelDo) WithContext(ctx context.Context) IPrfFlowerLevelDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p prfFlowerLevelDo) ReadDB() IPrfFlowerLevelDo {
	return p.Clauses(dbresolver.Read)
}

func (p prfFlowerLevelDo) WriteDB() IPrfFlowerLevelDo {
	return p.Clauses(dbresolver.Write)
}

func (p prfFlowerLevelDo) Session(config *gorm.Session) IPrfFlowerLevelDo {
	return p.withDO(p.DO.Session(config))
}

func (p prfFlowerLevelDo) Clauses(conds ...clause.Expression) IPrfFlowerLevelDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p prfFlowerLevelDo) Returning(value interface{}, columns ...string) IPrfFlowerLevelDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p prfFlowerLevelDo) Not(conds ...gen.Condition) IPrfFlowerLevelDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p prfFlowerLevelDo) Or(conds ...gen.Condition) IPrfFlowerLevelDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p prfFlowerLevelDo) Select(conds ...field.Expr) IPrfFlowerLevelDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p prfFlowerLevelDo) Where(conds ...gen.Condition) IPrfFlowerLevelDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p prfFlowerLevelDo) Order(conds ...field.Expr) IPrfFlowerLevelDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p prfFlowerLevelDo) Distinct(cols ...field.Expr) IPrfFlowerLevelDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p prfFlowerLevelDo) Omit(cols ...field.Expr) IPrfFlowerLevelDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p prfFlowerLevelDo) Join(table schema.Tabler, on ...field.Expr) IPrfFlowerLevelDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p prfFlowerLevelDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPrfFlowerLevelDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p prfFlowerLevelDo) RightJoin(table schema.Tabler, on ...field.Expr) IPrfFlowerLevelDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p prfFlowerLevelDo) Group(cols ...field.Expr) IPrfFlowerLevelDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p prfFlowerLevelDo) Having(conds ...gen.Condition) IPrfFlowerLevelDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p prfFlowerLevelDo) Limit(limit int) IPrfFlowerLevelDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p prfFlowerLevelDo) Offset(offset int) IPrfFlowerLevelDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p prfFlowerLevelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPrfFlowerLevelDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p prfFlowerLevelDo) Unscoped() IPrfFlowerLevelDo {
	return p.withDO(p.DO.Unscoped())
}

func (p prfFlowerLevelDo) Create(values ...*model.PrfFlowerLevel) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p prfFlowerLevelDo) CreateInBatches(values []*model.PrfFlowerLevel, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p prfFlowerLevelDo) Save(values ...*model.PrfFlowerLevel) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p prfFlowerLevelDo) First() (*model.PrfFlowerLevel, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrfFlowerLevel), nil
	}
}

func (p prfFlowerLevelDo) Take() (*model.PrfFlowerLevel, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrfFlowerLevel), nil
	}
}

func (p prfFlowerLevelDo) Last() (*model.PrfFlowerLevel, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrfFlowerLevel), nil
	}
}

func (p prfFlowerLevelDo) Find() ([]*model.PrfFlowerLevel, error) {
	result, err := p.DO.Find()
	return result.([]*model.PrfFlowerLevel), err
}

func (p prfFlowerLevelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PrfFlowerLevel, err error) {
	buf := make([]*model.PrfFlowerLevel, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p prfFlowerLevelDo) FindInBatches(result *[]*model.PrfFlowerLevel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p prfFlowerLevelDo) Attrs(attrs ...field.AssignExpr) IPrfFlowerLevelDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p prfFlowerLevelDo) Assign(attrs ...field.AssignExpr) IPrfFlowerLevelDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p prfFlowerLevelDo) Joins(fields ...field.RelationField) IPrfFlowerLevelDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p prfFlowerLevelDo) Preload(fields ...field.RelationField) IPrfFlowerLevelDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p prfFlowerLevelDo) FirstOrInit() (*model.PrfFlowerLevel, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrfFlowerLevel), nil
	}
}

func (p prfFlowerLevelDo) FirstOrCreate() (*model.PrfFlowerLevel, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrfFlowerLevel), nil
	}
}

func (p prfFlowerLevelDo) FindByPage(offset int, limit int) (result []*model.PrfFlowerLevel, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p prfFlowerLevelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p prfFlowerLevelDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p prfFlowerLevelDo) Delete(models ...*model.PrfFlowerLevel) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *prfFlowerLevelDo) withDO(do gen.Dao) *prfFlowerLevelDo {
	p.DO = *do.(*gen.DO)
	return p
}
