// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"server_gin/dao/model"
)

func newPrfFlower(db *gorm.DB, opts ...gen.DOOption) prfFlower {
	_prfFlower := prfFlower{}

	_prfFlower.prfFlowerDo.UseDB(db, opts...)
	_prfFlower.prfFlowerDo.UseModel(&model.PrfFlower{})

	tableName := _prfFlower.prfFlowerDo.TableName()
	_prfFlower.ALL = field.NewAsterisk(tableName)
	_prfFlower.ID = field.NewInt32(tableName, "id")
	_prfFlower.Name = field.NewString(tableName, "name")
	_prfFlower.Des = field.NewString(tableName, "des")
	_prfFlower.From = field.NewInt32(tableName, "from")
	_prfFlower.FromTip = field.NewString(tableName, "from_tip")
	_prfFlower.Index = field.NewInt32(tableName, "index")
	_prfFlower.SellRes = field.NewString(tableName, "sell_res")
	_prfFlower.Water = field.NewInt32(tableName, "water")
	_prfFlower.Cost = field.NewString(tableName, "cost")
	_prfFlower.Cd = field.NewInt32(tableName, "cd")
	_prfFlower.Qua = field.NewInt32(tableName, "qua")
	_prfFlower.Charm = field.NewInt32(tableName, "charm")
	_prfFlower.Pic0 = field.NewString(tableName, "pic_0")
	_prfFlower.Pic1 = field.NewString(tableName, "pic_1")
	_prfFlower.Pic2 = field.NewString(tableName, "pic_2")
	_prfFlower.Pic3 = field.NewString(tableName, "pic_3")
	_prfFlower.Pic4 = field.NewString(tableName, "pic_4")
	_prfFlower.Pic5 = field.NewString(tableName, "pic_5")
	_prfFlower.Pic6 = field.NewString(tableName, "pic_6")
	_prfFlower.Pic7 = field.NewString(tableName, "pic_7")
	_prfFlower.PicLand = field.NewString(tableName, "pic_land")
	_prfFlower.SpineFlowerLand = field.NewString(tableName, "spine_flower_land")
	_prfFlower.SpineLand = field.NewString(tableName, "spine_land")
	_prfFlower.SpineFlowerBook = field.NewString(tableName, "spine_flower_book")
	_prfFlower.SpineFlowerBookExtra = field.NewString(tableName, "spine_flower_book_extra")
	_prfFlower.NoBottle = field.NewInt32(tableName, "no_bottle")

	_prfFlower.fillFieldMap()

	return _prfFlower
}

type prfFlower struct {
	prfFlowerDo

	ALL  field.Asterisk
	ID   field.Int32
	Name field.String // 花的名字
	Des  field.String // 花语
	/*
		0=升级解锁
		1=测试用
		2=活动获得
		3=鲜花礼包
		4=徐霞客处获得
		5=VIP专享
		6=公会获得
		7=敬请期待
		8=已绝版
	*/
	From                 field.Int32
	FromTip              field.String // 来源提示
	Index                field.Int32  // 排序
	SellRes              field.String // 出售获得的资源，类型,id,数量
	Water                field.Int32  // 种植消耗的水滴
	Cost                 field.String // 培育所需资源
	Cd                   field.Int32  // 培育所需时间
	Qua                  field.Int32  // 品质。1=绿色，2=蓝色，3=紫色，4=红色，5=金色
	Charm                field.Int32  // 魅力值
	Pic0                 field.String // 培育房-种子、收割-掉落的种子、鲜花升级-卡片种子
	Pic1                 field.String // 种地-刚刚播种
	Pic2                 field.String // 种地-长了一半
	Pic3                 field.String // 种地-完全长成、徐霞客、社团种植花盆内
	Pic4                 field.String // 收割-掉在地上
	Pic5                 field.String // 培育房-培育花台缩略图、仓库-缩略图、播种选择页、鲜花订单、插花、社团种植收取、好友交易、按住播种
	Pic6                 field.String // 花谱-外层显示、花市订单
	Pic7                 field.String // 花谱-带花瓶
	PicLand              field.String // 土地图片
	SpineFlowerLand      field.String // 种在地里的花动画
	SpineLand            field.String // 地块动画
	SpineFlowerBook      field.String // 图鉴花动画
	SpineFlowerBookExtra field.String // 图鉴花动画-附加
	NoBottle             field.Int32  // 不显示瓶子

	fieldMap map[string]field.Expr
}

func (p prfFlower) Table(newTableName string) *prfFlower {
	p.prfFlowerDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p prfFlower) As(alias string) *prfFlower {
	p.prfFlowerDo.DO = *(p.prfFlowerDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *prfFlower) updateTableName(table string) *prfFlower {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt32(table, "id")
	p.Name = field.NewString(table, "name")
	p.Des = field.NewString(table, "des")
	p.From = field.NewInt32(table, "from")
	p.FromTip = field.NewString(table, "from_tip")
	p.Index = field.NewInt32(table, "index")
	p.SellRes = field.NewString(table, "sell_res")
	p.Water = field.NewInt32(table, "water")
	p.Cost = field.NewString(table, "cost")
	p.Cd = field.NewInt32(table, "cd")
	p.Qua = field.NewInt32(table, "qua")
	p.Charm = field.NewInt32(table, "charm")
	p.Pic0 = field.NewString(table, "pic_0")
	p.Pic1 = field.NewString(table, "pic_1")
	p.Pic2 = field.NewString(table, "pic_2")
	p.Pic3 = field.NewString(table, "pic_3")
	p.Pic4 = field.NewString(table, "pic_4")
	p.Pic5 = field.NewString(table, "pic_5")
	p.Pic6 = field.NewString(table, "pic_6")
	p.Pic7 = field.NewString(table, "pic_7")
	p.PicLand = field.NewString(table, "pic_land")
	p.SpineFlowerLand = field.NewString(table, "spine_flower_land")
	p.SpineLand = field.NewString(table, "spine_land")
	p.SpineFlowerBook = field.NewString(table, "spine_flower_book")
	p.SpineFlowerBookExtra = field.NewString(table, "spine_flower_book_extra")
	p.NoBottle = field.NewInt32(table, "no_bottle")

	p.fillFieldMap()

	return p
}

func (p *prfFlower) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *prfFlower) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 26)
	p.fieldMap["id"] = p.ID
	p.fieldMap["name"] = p.Name
	p.fieldMap["des"] = p.Des
	p.fieldMap["from"] = p.From
	p.fieldMap["from_tip"] = p.FromTip
	p.fieldMap["index"] = p.Index
	p.fieldMap["sell_res"] = p.SellRes
	p.fieldMap["water"] = p.Water
	p.fieldMap["cost"] = p.Cost
	p.fieldMap["cd"] = p.Cd
	p.fieldMap["qua"] = p.Qua
	p.fieldMap["charm"] = p.Charm
	p.fieldMap["pic_0"] = p.Pic0
	p.fieldMap["pic_1"] = p.Pic1
	p.fieldMap["pic_2"] = p.Pic2
	p.fieldMap["pic_3"] = p.Pic3
	p.fieldMap["pic_4"] = p.Pic4
	p.fieldMap["pic_5"] = p.Pic5
	p.fieldMap["pic_6"] = p.Pic6
	p.fieldMap["pic_7"] = p.Pic7
	p.fieldMap["pic_land"] = p.PicLand
	p.fieldMap["spine_flower_land"] = p.SpineFlowerLand
	p.fieldMap["spine_land"] = p.SpineLand
	p.fieldMap["spine_flower_book"] = p.SpineFlowerBook
	p.fieldMap["spine_flower_book_extra"] = p.SpineFlowerBookExtra
	p.fieldMap["no_bottle"] = p.NoBottle
}

func (p prfFlower) clone(db *gorm.DB) prfFlower {
	p.prfFlowerDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p prfFlower) replaceDB(db *gorm.DB) prfFlower {
	p.prfFlowerDo.ReplaceDB(db)
	return p
}

type prfFlowerDo struct{ gen.DO }

type IPrfFlowerDo interface {
	gen.SubQuery
	Debug() IPrfFlowerDo
	WithContext(ctx context.Context) IPrfFlowerDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPrfFlowerDo
	WriteDB() IPrfFlowerDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPrfFlowerDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPrfFlowerDo
	Not(conds ...gen.Condition) IPrfFlowerDo
	Or(conds ...gen.Condition) IPrfFlowerDo
	Select(conds ...field.Expr) IPrfFlowerDo
	Where(conds ...gen.Condition) IPrfFlowerDo
	Order(conds ...field.Expr) IPrfFlowerDo
	Distinct(cols ...field.Expr) IPrfFlowerDo
	Omit(cols ...field.Expr) IPrfFlowerDo
	Join(table schema.Tabler, on ...field.Expr) IPrfFlowerDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPrfFlowerDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPrfFlowerDo
	Group(cols ...field.Expr) IPrfFlowerDo
	Having(conds ...gen.Condition) IPrfFlowerDo
	Limit(limit int) IPrfFlowerDo
	Offset(offset int) IPrfFlowerDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPrfFlowerDo
	Unscoped() IPrfFlowerDo
	Create(values ...*model.PrfFlower) error
	CreateInBatches(values []*model.PrfFlower, batchSize int) error
	Save(values ...*model.PrfFlower) error
	First() (*model.PrfFlower, error)
	Take() (*model.PrfFlower, error)
	Last() (*model.PrfFlower, error)
	Find() ([]*model.PrfFlower, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PrfFlower, err error)
	FindInBatches(result *[]*model.PrfFlower, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PrfFlower) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPrfFlowerDo
	Assign(attrs ...field.AssignExpr) IPrfFlowerDo
	Joins(fields ...field.RelationField) IPrfFlowerDo
	Preload(fields ...field.RelationField) IPrfFlowerDo
	FirstOrInit() (*model.PrfFlower, error)
	FirstOrCreate() (*model.PrfFlower, error)
	FindByPage(offset int, limit int) (result []*model.PrfFlower, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPrfFlowerDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p prfFlowerDo) Debug() IPrfFlowerDo {
	return p.withDO(p.DO.Debug())
}

func (p prfFlowerDo) WithContext(ctx context.Context) IPrfFlowerDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p prfFlowerDo) ReadDB() IPrfFlowerDo {
	return p.Clauses(dbresolver.Read)
}

func (p prfFlowerDo) WriteDB() IPrfFlowerDo {
	return p.Clauses(dbresolver.Write)
}

func (p prfFlowerDo) Session(config *gorm.Session) IPrfFlowerDo {
	return p.withDO(p.DO.Session(config))
}

func (p prfFlowerDo) Clauses(conds ...clause.Expression) IPrfFlowerDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p prfFlowerDo) Returning(value interface{}, columns ...string) IPrfFlowerDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p prfFlowerDo) Not(conds ...gen.Condition) IPrfFlowerDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p prfFlowerDo) Or(conds ...gen.Condition) IPrfFlowerDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p prfFlowerDo) Select(conds ...field.Expr) IPrfFlowerDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p prfFlowerDo) Where(conds ...gen.Condition) IPrfFlowerDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p prfFlowerDo) Order(conds ...field.Expr) IPrfFlowerDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p prfFlowerDo) Distinct(cols ...field.Expr) IPrfFlowerDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p prfFlowerDo) Omit(cols ...field.Expr) IPrfFlowerDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p prfFlowerDo) Join(table schema.Tabler, on ...field.Expr) IPrfFlowerDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p prfFlowerDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPrfFlowerDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p prfFlowerDo) RightJoin(table schema.Tabler, on ...field.Expr) IPrfFlowerDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p prfFlowerDo) Group(cols ...field.Expr) IPrfFlowerDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p prfFlowerDo) Having(conds ...gen.Condition) IPrfFlowerDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p prfFlowerDo) Limit(limit int) IPrfFlowerDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p prfFlowerDo) Offset(offset int) IPrfFlowerDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p prfFlowerDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPrfFlowerDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p prfFlowerDo) Unscoped() IPrfFlowerDo {
	return p.withDO(p.DO.Unscoped())
}

func (p prfFlowerDo) Create(values ...*model.PrfFlower) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p prfFlowerDo) CreateInBatches(values []*model.PrfFlower, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p prfFlowerDo) Save(values ...*model.PrfFlower) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p prfFlowerDo) First() (*model.PrfFlower, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrfFlower), nil
	}
}

func (p prfFlowerDo) Take() (*model.PrfFlower, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrfFlower), nil
	}
}

func (p prfFlowerDo) Last() (*model.PrfFlower, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrfFlower), nil
	}
}

func (p prfFlowerDo) Find() ([]*model.PrfFlower, error) {
	result, err := p.DO.Find()
	return result.([]*model.PrfFlower), err
}

func (p prfFlowerDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PrfFlower, err error) {
	buf := make([]*model.PrfFlower, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p prfFlowerDo) FindInBatches(result *[]*model.PrfFlower, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p prfFlowerDo) Attrs(attrs ...field.AssignExpr) IPrfFlowerDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p prfFlowerDo) Assign(attrs ...field.AssignExpr) IPrfFlowerDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p prfFlowerDo) Joins(fields ...field.RelationField) IPrfFlowerDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p prfFlowerDo) Preload(fields ...field.RelationField) IPrfFlowerDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p prfFlowerDo) FirstOrInit() (*model.PrfFlower, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrfFlower), nil
	}
}

func (p prfFlowerDo) FirstOrCreate() (*model.PrfFlower, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrfFlower), nil
	}
}

func (p prfFlowerDo) FindByPage(offset int, limit int) (result []*model.PrfFlower, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p prfFlowerDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p prfFlowerDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p prfFlowerDo) Delete(models ...*model.PrfFlower) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *prfFlowerDo) withDO(do gen.Dao) *prfFlowerDo {
	p.DO = *do.(*gen.DO)
	return p
}
