// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"server_gin/dao/model"
)

func newPrfTask(db *gorm.DB, opts ...gen.DOOption) prfTask {
	_prfTask := prfTask{}

	_prfTask.prfTaskDo.UseDB(db, opts...)
	_prfTask.prfTaskDo.UseModel(&model.PrfTask{})

	tableName := _prfTask.prfTaskDo.TableName()
	_prfTask.ALL = field.NewAsterisk(tableName)
	_prfTask.ID = field.NewInt32(tableName, "id")
	_prfTask.Ser = field.NewInt32(tableName, "ser")
	_prfTask.Tid = field.NewString(tableName, "tid")
	_prfTask.Npc = field.NewInt32(tableName, "npc")
	_prfTask.StartLoop = field.NewInt32(tableName, "start_loop")

	_prfTask.fillFieldMap()

	return _prfTask
}

type prfTask struct {
	prfTaskDo

	ALL       field.Asterisk
	ID        field.Int32
	Ser       field.Int32  // 对应工厂的ser
	Tid       field.String // 任务道具id
	Npc       field.Int32
	StartLoop field.Int32 // 开启循环的第一个任务有效,每组里如果都是0,不开启循环

	fieldMap map[string]field.Expr
}

func (p prfTask) Table(newTableName string) *prfTask {
	p.prfTaskDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p prfTask) As(alias string) *prfTask {
	p.prfTaskDo.DO = *(p.prfTaskDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *prfTask) updateTableName(table string) *prfTask {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt32(table, "id")
	p.Ser = field.NewInt32(table, "ser")
	p.Tid = field.NewString(table, "tid")
	p.Npc = field.NewInt32(table, "npc")
	p.StartLoop = field.NewInt32(table, "start_loop")

	p.fillFieldMap()

	return p
}

func (p *prfTask) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *prfTask) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 5)
	p.fieldMap["id"] = p.ID
	p.fieldMap["ser"] = p.Ser
	p.fieldMap["tid"] = p.Tid
	p.fieldMap["npc"] = p.Npc
	p.fieldMap["start_loop"] = p.StartLoop
}

func (p prfTask) clone(db *gorm.DB) prfTask {
	p.prfTaskDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p prfTask) replaceDB(db *gorm.DB) prfTask {
	p.prfTaskDo.ReplaceDB(db)
	return p
}

type prfTaskDo struct{ gen.DO }

type IPrfTaskDo interface {
	gen.SubQuery
	Debug() IPrfTaskDo
	WithContext(ctx context.Context) IPrfTaskDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPrfTaskDo
	WriteDB() IPrfTaskDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPrfTaskDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPrfTaskDo
	Not(conds ...gen.Condition) IPrfTaskDo
	Or(conds ...gen.Condition) IPrfTaskDo
	Select(conds ...field.Expr) IPrfTaskDo
	Where(conds ...gen.Condition) IPrfTaskDo
	Order(conds ...field.Expr) IPrfTaskDo
	Distinct(cols ...field.Expr) IPrfTaskDo
	Omit(cols ...field.Expr) IPrfTaskDo
	Join(table schema.Tabler, on ...field.Expr) IPrfTaskDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPrfTaskDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPrfTaskDo
	Group(cols ...field.Expr) IPrfTaskDo
	Having(conds ...gen.Condition) IPrfTaskDo
	Limit(limit int) IPrfTaskDo
	Offset(offset int) IPrfTaskDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPrfTaskDo
	Unscoped() IPrfTaskDo
	Create(values ...*model.PrfTask) error
	CreateInBatches(values []*model.PrfTask, batchSize int) error
	Save(values ...*model.PrfTask) error
	First() (*model.PrfTask, error)
	Take() (*model.PrfTask, error)
	Last() (*model.PrfTask, error)
	Find() ([]*model.PrfTask, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PrfTask, err error)
	FindInBatches(result *[]*model.PrfTask, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PrfTask) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPrfTaskDo
	Assign(attrs ...field.AssignExpr) IPrfTaskDo
	Joins(fields ...field.RelationField) IPrfTaskDo
	Preload(fields ...field.RelationField) IPrfTaskDo
	FirstOrInit() (*model.PrfTask, error)
	FirstOrCreate() (*model.PrfTask, error)
	FindByPage(offset int, limit int) (result []*model.PrfTask, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPrfTaskDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p prfTaskDo) Debug() IPrfTaskDo {
	return p.withDO(p.DO.Debug())
}

func (p prfTaskDo) WithContext(ctx context.Context) IPrfTaskDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p prfTaskDo) ReadDB() IPrfTaskDo {
	return p.Clauses(dbresolver.Read)
}

func (p prfTaskDo) WriteDB() IPrfTaskDo {
	return p.Clauses(dbresolver.Write)
}

func (p prfTaskDo) Session(config *gorm.Session) IPrfTaskDo {
	return p.withDO(p.DO.Session(config))
}

func (p prfTaskDo) Clauses(conds ...clause.Expression) IPrfTaskDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p prfTaskDo) Returning(value interface{}, columns ...string) IPrfTaskDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p prfTaskDo) Not(conds ...gen.Condition) IPrfTaskDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p prfTaskDo) Or(conds ...gen.Condition) IPrfTaskDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p prfTaskDo) Select(conds ...field.Expr) IPrfTaskDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p prfTaskDo) Where(conds ...gen.Condition) IPrfTaskDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p prfTaskDo) Order(conds ...field.Expr) IPrfTaskDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p prfTaskDo) Distinct(cols ...field.Expr) IPrfTaskDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p prfTaskDo) Omit(cols ...field.Expr) IPrfTaskDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p prfTaskDo) Join(table schema.Tabler, on ...field.Expr) IPrfTaskDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p prfTaskDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPrfTaskDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p prfTaskDo) RightJoin(table schema.Tabler, on ...field.Expr) IPrfTaskDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p prfTaskDo) Group(cols ...field.Expr) IPrfTaskDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p prfTaskDo) Having(conds ...gen.Condition) IPrfTaskDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p prfTaskDo) Limit(limit int) IPrfTaskDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p prfTaskDo) Offset(offset int) IPrfTaskDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p prfTaskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPrfTaskDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p prfTaskDo) Unscoped() IPrfTaskDo {
	return p.withDO(p.DO.Unscoped())
}

func (p prfTaskDo) Create(values ...*model.PrfTask) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p prfTaskDo) CreateInBatches(values []*model.PrfTask, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p prfTaskDo) Save(values ...*model.PrfTask) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p prfTaskDo) First() (*model.PrfTask, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrfTask), nil
	}
}

func (p prfTaskDo) Take() (*model.PrfTask, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrfTask), nil
	}
}

func (p prfTaskDo) Last() (*model.PrfTask, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrfTask), nil
	}
}

func (p prfTaskDo) Find() ([]*model.PrfTask, error) {
	result, err := p.DO.Find()
	return result.([]*model.PrfTask), err
}

func (p prfTaskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PrfTask, err error) {
	buf := make([]*model.PrfTask, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p prfTaskDo) FindInBatches(result *[]*model.PrfTask, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p prfTaskDo) Attrs(attrs ...field.AssignExpr) IPrfTaskDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p prfTaskDo) Assign(attrs ...field.AssignExpr) IPrfTaskDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p prfTaskDo) Joins(fields ...field.RelationField) IPrfTaskDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p prfTaskDo) Preload(fields ...field.RelationField) IPrfTaskDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p prfTaskDo) FirstOrInit() (*model.PrfTask, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrfTask), nil
	}
}

func (p prfTaskDo) FirstOrCreate() (*model.PrfTask, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrfTask), nil
	}
}

func (p prfTaskDo) FindByPage(offset int, limit int) (result []*model.PrfTask, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p prfTaskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p prfTaskDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p prfTaskDo) Delete(models ...*model.PrfTask) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *prfTaskDo) withDO(do gen.Dao) *prfTaskDo {
	p.DO = *do.(*gen.DO)
	return p
}
