// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"server_go/dao/model"
)

func newSysDie(db *gorm.DB, opts ...gen.DOOption) sysDie {
	_sysDie := sysDie{}

	_sysDie.sysDieDo.UseDB(db, opts...)
	_sysDie.sysDieDo.UseModel(&model.SysDie{})

	tableName := _sysDie.sysDieDo.TableName()
	_sysDie.ALL = field.NewAsterisk(tableName)
	_sysDie.UID = field.NewInt32(tableName, "uid")
	_sysDie.Tips = field.NewString(tableName, "tips")
	_sysDie.Time = field.NewTime(tableName, "time")

	_sysDie.fillFieldMap()

	return _sysDie
}

// sysDie 被封掉的用户
type sysDie struct {
	sysDieDo

	ALL  field.Asterisk
	UID  field.Int32
	Tips field.String // 封掉用户登陆时候的错误提示
	Time field.Time

	fieldMap map[string]field.Expr
}

func (s sysDie) Table(newTableName string) *sysDie {
	s.sysDieDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysDie) As(alias string) *sysDie {
	s.sysDieDo.DO = *(s.sysDieDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysDie) updateTableName(table string) *sysDie {
	s.ALL = field.NewAsterisk(table)
	s.UID = field.NewInt32(table, "uid")
	s.Tips = field.NewString(table, "tips")
	s.Time = field.NewTime(table, "time")

	s.fillFieldMap()

	return s
}

func (s *sysDie) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysDie) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 3)
	s.fieldMap["uid"] = s.UID
	s.fieldMap["tips"] = s.Tips
	s.fieldMap["time"] = s.Time
}

func (s sysDie) clone(db *gorm.DB) sysDie {
	s.sysDieDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysDie) replaceDB(db *gorm.DB) sysDie {
	s.sysDieDo.ReplaceDB(db)
	return s
}

type sysDieDo struct{ gen.DO }

type ISysDieDo interface {
	gen.SubQuery
	Debug() ISysDieDo
	WithContext(ctx context.Context) ISysDieDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysDieDo
	WriteDB() ISysDieDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysDieDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysDieDo
	Not(conds ...gen.Condition) ISysDieDo
	Or(conds ...gen.Condition) ISysDieDo
	Select(conds ...field.Expr) ISysDieDo
	Where(conds ...gen.Condition) ISysDieDo
	Order(conds ...field.Expr) ISysDieDo
	Distinct(cols ...field.Expr) ISysDieDo
	Omit(cols ...field.Expr) ISysDieDo
	Join(table schema.Tabler, on ...field.Expr) ISysDieDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysDieDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysDieDo
	Group(cols ...field.Expr) ISysDieDo
	Having(conds ...gen.Condition) ISysDieDo
	Limit(limit int) ISysDieDo
	Offset(offset int) ISysDieDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysDieDo
	Unscoped() ISysDieDo
	Create(values ...*model.SysDie) error
	CreateInBatches(values []*model.SysDie, batchSize int) error
	Save(values ...*model.SysDie) error
	First() (*model.SysDie, error)
	Take() (*model.SysDie, error)
	Last() (*model.SysDie, error)
	Find() ([]*model.SysDie, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysDie, err error)
	FindInBatches(result *[]*model.SysDie, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysDie) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysDieDo
	Assign(attrs ...field.AssignExpr) ISysDieDo
	Joins(fields ...field.RelationField) ISysDieDo
	Preload(fields ...field.RelationField) ISysDieDo
	FirstOrInit() (*model.SysDie, error)
	FirstOrCreate() (*model.SysDie, error)
	FindByPage(offset int, limit int) (result []*model.SysDie, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysDieDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysDieDo) Debug() ISysDieDo {
	return s.withDO(s.DO.Debug())
}

func (s sysDieDo) WithContext(ctx context.Context) ISysDieDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysDieDo) ReadDB() ISysDieDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysDieDo) WriteDB() ISysDieDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysDieDo) Session(config *gorm.Session) ISysDieDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysDieDo) Clauses(conds ...clause.Expression) ISysDieDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysDieDo) Returning(value interface{}, columns ...string) ISysDieDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysDieDo) Not(conds ...gen.Condition) ISysDieDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysDieDo) Or(conds ...gen.Condition) ISysDieDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysDieDo) Select(conds ...field.Expr) ISysDieDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysDieDo) Where(conds ...gen.Condition) ISysDieDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysDieDo) Order(conds ...field.Expr) ISysDieDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysDieDo) Distinct(cols ...field.Expr) ISysDieDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysDieDo) Omit(cols ...field.Expr) ISysDieDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysDieDo) Join(table schema.Tabler, on ...field.Expr) ISysDieDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysDieDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysDieDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysDieDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysDieDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysDieDo) Group(cols ...field.Expr) ISysDieDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysDieDo) Having(conds ...gen.Condition) ISysDieDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysDieDo) Limit(limit int) ISysDieDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysDieDo) Offset(offset int) ISysDieDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysDieDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysDieDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysDieDo) Unscoped() ISysDieDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysDieDo) Create(values ...*model.SysDie) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysDieDo) CreateInBatches(values []*model.SysDie, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysDieDo) Save(values ...*model.SysDie) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysDieDo) First() (*model.SysDie, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDie), nil
	}
}

func (s sysDieDo) Take() (*model.SysDie, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDie), nil
	}
}

func (s sysDieDo) Last() (*model.SysDie, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDie), nil
	}
}

func (s sysDieDo) Find() ([]*model.SysDie, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysDie), err
}

func (s sysDieDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysDie, err error) {
	buf := make([]*model.SysDie, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysDieDo) FindInBatches(result *[]*model.SysDie, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysDieDo) Attrs(attrs ...field.AssignExpr) ISysDieDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysDieDo) Assign(attrs ...field.AssignExpr) ISysDieDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysDieDo) Joins(fields ...field.RelationField) ISysDieDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysDieDo) Preload(fields ...field.RelationField) ISysDieDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysDieDo) FirstOrInit() (*model.SysDie, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDie), nil
	}
}

func (s sysDieDo) FirstOrCreate() (*model.SysDie, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDie), nil
	}
}

func (s sysDieDo) FindByPage(offset int, limit int) (result []*model.SysDie, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysDieDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysDieDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysDieDo) Delete(models ...*model.SysDie) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysDieDo) withDO(do gen.Dao) *sysDieDo {
	s.DO = *do.(*gen.DO)
	return s
}
