// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"server_go/dao/model"
)

func newSysGm(db *gorm.DB, opts ...gen.DOOption) sysGm {
	_sysGm := sysGm{}

	_sysGm.sysGmDo.UseDB(db, opts...)
	_sysGm.sysGmDo.UseModel(&model.SysGm{})

	tableName := _sysGm.sysGmDo.TableName()
	_sysGm.ALL = field.NewAsterisk(tableName)
	_sysGm.UID = field.NewInt64(tableName, "uid")
	_sysGm.Tips = field.NewString(tableName, "tips")
	_sysGm.Time = field.NewTime(tableName, "time")

	_sysGm.fillFieldMap()

	return _sysGm
}

// sysGm gm用户
type sysGm struct {
	sysGmDo

	ALL  field.Asterisk
	UID  field.Int64
	Tips field.String
	Time field.Time

	fieldMap map[string]field.Expr
}

func (s sysGm) Table(newTableName string) *sysGm {
	s.sysGmDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysGm) As(alias string) *sysGm {
	s.sysGmDo.DO = *(s.sysGmDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysGm) updateTableName(table string) *sysGm {
	s.ALL = field.NewAsterisk(table)
	s.UID = field.NewInt64(table, "uid")
	s.Tips = field.NewString(table, "tips")
	s.Time = field.NewTime(table, "time")

	s.fillFieldMap()

	return s
}

func (s *sysGm) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysGm) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 3)
	s.fieldMap["uid"] = s.UID
	s.fieldMap["tips"] = s.Tips
	s.fieldMap["time"] = s.Time
}

func (s sysGm) clone(db *gorm.DB) sysGm {
	s.sysGmDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysGm) replaceDB(db *gorm.DB) sysGm {
	s.sysGmDo.ReplaceDB(db)
	return s
}

type sysGmDo struct{ gen.DO }

type ISysGmDo interface {
	gen.SubQuery
	Debug() ISysGmDo
	WithContext(ctx context.Context) ISysGmDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysGmDo
	WriteDB() ISysGmDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysGmDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysGmDo
	Not(conds ...gen.Condition) ISysGmDo
	Or(conds ...gen.Condition) ISysGmDo
	Select(conds ...field.Expr) ISysGmDo
	Where(conds ...gen.Condition) ISysGmDo
	Order(conds ...field.Expr) ISysGmDo
	Distinct(cols ...field.Expr) ISysGmDo
	Omit(cols ...field.Expr) ISysGmDo
	Join(table schema.Tabler, on ...field.Expr) ISysGmDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysGmDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysGmDo
	Group(cols ...field.Expr) ISysGmDo
	Having(conds ...gen.Condition) ISysGmDo
	Limit(limit int) ISysGmDo
	Offset(offset int) ISysGmDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysGmDo
	Unscoped() ISysGmDo
	Create(values ...*model.SysGm) error
	CreateInBatches(values []*model.SysGm, batchSize int) error
	Save(values ...*model.SysGm) error
	First() (*model.SysGm, error)
	Take() (*model.SysGm, error)
	Last() (*model.SysGm, error)
	Find() ([]*model.SysGm, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysGm, err error)
	FindInBatches(result *[]*model.SysGm, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysGm) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysGmDo
	Assign(attrs ...field.AssignExpr) ISysGmDo
	Joins(fields ...field.RelationField) ISysGmDo
	Preload(fields ...field.RelationField) ISysGmDo
	FirstOrInit() (*model.SysGm, error)
	FirstOrCreate() (*model.SysGm, error)
	FindByPage(offset int, limit int) (result []*model.SysGm, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysGmDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysGmDo) Debug() ISysGmDo {
	return s.withDO(s.DO.Debug())
}

func (s sysGmDo) WithContext(ctx context.Context) ISysGmDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysGmDo) ReadDB() ISysGmDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysGmDo) WriteDB() ISysGmDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysGmDo) Session(config *gorm.Session) ISysGmDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysGmDo) Clauses(conds ...clause.Expression) ISysGmDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysGmDo) Returning(value interface{}, columns ...string) ISysGmDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysGmDo) Not(conds ...gen.Condition) ISysGmDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysGmDo) Or(conds ...gen.Condition) ISysGmDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysGmDo) Select(conds ...field.Expr) ISysGmDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysGmDo) Where(conds ...gen.Condition) ISysGmDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysGmDo) Order(conds ...field.Expr) ISysGmDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysGmDo) Distinct(cols ...field.Expr) ISysGmDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysGmDo) Omit(cols ...field.Expr) ISysGmDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysGmDo) Join(table schema.Tabler, on ...field.Expr) ISysGmDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysGmDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysGmDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysGmDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysGmDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysGmDo) Group(cols ...field.Expr) ISysGmDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysGmDo) Having(conds ...gen.Condition) ISysGmDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysGmDo) Limit(limit int) ISysGmDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysGmDo) Offset(offset int) ISysGmDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysGmDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysGmDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysGmDo) Unscoped() ISysGmDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysGmDo) Create(values ...*model.SysGm) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysGmDo) CreateInBatches(values []*model.SysGm, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysGmDo) Save(values ...*model.SysGm) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysGmDo) First() (*model.SysGm, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysGm), nil
	}
}

func (s sysGmDo) Take() (*model.SysGm, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysGm), nil
	}
}

func (s sysGmDo) Last() (*model.SysGm, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysGm), nil
	}
}

func (s sysGmDo) Find() ([]*model.SysGm, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysGm), err
}

func (s sysGmDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysGm, err error) {
	buf := make([]*model.SysGm, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysGmDo) FindInBatches(result *[]*model.SysGm, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysGmDo) Attrs(attrs ...field.AssignExpr) ISysGmDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysGmDo) Assign(attrs ...field.AssignExpr) ISysGmDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysGmDo) Joins(fields ...field.RelationField) ISysGmDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysGmDo) Preload(fields ...field.RelationField) ISysGmDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysGmDo) FirstOrInit() (*model.SysGm, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysGm), nil
	}
}

func (s sysGmDo) FirstOrCreate() (*model.SysGm, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysGm), nil
	}
}

func (s sysGmDo) FindByPage(offset int, limit int) (result []*model.SysGm, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysGmDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysGmDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysGmDo) Delete(models ...*model.SysGm) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysGmDo) withDO(do gen.Dao) *sysGmDo {
	s.DO = *do.(*gen.DO)
	return s
}
