// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"server_gin/dao/model"
)

func newUserRes(db *gorm.DB, opts ...gen.DOOption) userRes {
	_userRes := userRes{}

	_userRes.userResDo.UseDB(db, opts...)
	_userRes.userResDo.UseModel(&model.UserRes{})

	tableName := _userRes.userResDo.TableName()
	_userRes.ALL = field.NewAsterisk(tableName)
	_userRes.UID = field.NewInt32(tableName, "uid")
	_userRes.Gold = field.NewInt32(tableName, "gold")
	_userRes.Diamond = field.NewInt32(tableName, "diamond")
	_userRes.Star = field.NewInt32(tableName, "star")
	_userRes.Tili = field.NewInt32(tableName, "tili")
	_userRes.TiliTime = field.NewInt32(tableName, "tili_time")
	_userRes.Exp = field.NewInt32(tableName, "exp")
	_userRes.Level = field.NewInt32(tableName, "level")
	_userRes.DayConf = field.NewString(tableName, "day_conf")
	_userRes.DayTime = field.NewInt32(tableName, "day_time")

	_userRes.fillFieldMap()

	return _userRes
}

type userRes struct {
	userResDo

	ALL      field.Asterisk
	UID      field.Int32
	Gold     field.Int32
	Diamond  field.Int32
	Star     field.Int32
	Tili     field.Int32
	TiliTime field.Int32
	Exp      field.Int32
	Level    field.Int32
	DayConf  field.String // 每日重置的数据
	DayTime  field.Int32  // 上次重置时间

	fieldMap map[string]field.Expr
}

func (u userRes) Table(newTableName string) *userRes {
	u.userResDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userRes) As(alias string) *userRes {
	u.userResDo.DO = *(u.userResDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userRes) updateTableName(table string) *userRes {
	u.ALL = field.NewAsterisk(table)
	u.UID = field.NewInt32(table, "uid")
	u.Gold = field.NewInt32(table, "gold")
	u.Diamond = field.NewInt32(table, "diamond")
	u.Star = field.NewInt32(table, "star")
	u.Tili = field.NewInt32(table, "tili")
	u.TiliTime = field.NewInt32(table, "tili_time")
	u.Exp = field.NewInt32(table, "exp")
	u.Level = field.NewInt32(table, "level")
	u.DayConf = field.NewString(table, "day_conf")
	u.DayTime = field.NewInt32(table, "day_time")

	u.fillFieldMap()

	return u
}

func (u *userRes) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userRes) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 10)
	u.fieldMap["uid"] = u.UID
	u.fieldMap["gold"] = u.Gold
	u.fieldMap["diamond"] = u.Diamond
	u.fieldMap["star"] = u.Star
	u.fieldMap["tili"] = u.Tili
	u.fieldMap["tili_time"] = u.TiliTime
	u.fieldMap["exp"] = u.Exp
	u.fieldMap["level"] = u.Level
	u.fieldMap["day_conf"] = u.DayConf
	u.fieldMap["day_time"] = u.DayTime
}

func (u userRes) clone(db *gorm.DB) userRes {
	u.userResDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userRes) replaceDB(db *gorm.DB) userRes {
	u.userResDo.ReplaceDB(db)
	return u
}

type userResDo struct{ gen.DO }

type IUserResDo interface {
	gen.SubQuery
	Debug() IUserResDo
	WithContext(ctx context.Context) IUserResDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserResDo
	WriteDB() IUserResDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserResDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserResDo
	Not(conds ...gen.Condition) IUserResDo
	Or(conds ...gen.Condition) IUserResDo
	Select(conds ...field.Expr) IUserResDo
	Where(conds ...gen.Condition) IUserResDo
	Order(conds ...field.Expr) IUserResDo
	Distinct(cols ...field.Expr) IUserResDo
	Omit(cols ...field.Expr) IUserResDo
	Join(table schema.Tabler, on ...field.Expr) IUserResDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserResDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserResDo
	Group(cols ...field.Expr) IUserResDo
	Having(conds ...gen.Condition) IUserResDo
	Limit(limit int) IUserResDo
	Offset(offset int) IUserResDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserResDo
	Unscoped() IUserResDo
	Create(values ...*model.UserRes) error
	CreateInBatches(values []*model.UserRes, batchSize int) error
	Save(values ...*model.UserRes) error
	First() (*model.UserRes, error)
	Take() (*model.UserRes, error)
	Last() (*model.UserRes, error)
	Find() ([]*model.UserRes, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserRes, err error)
	FindInBatches(result *[]*model.UserRes, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.UserRes) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserResDo
	Assign(attrs ...field.AssignExpr) IUserResDo
	Joins(fields ...field.RelationField) IUserResDo
	Preload(fields ...field.RelationField) IUserResDo
	FirstOrInit() (*model.UserRes, error)
	FirstOrCreate() (*model.UserRes, error)
	FindByPage(offset int, limit int) (result []*model.UserRes, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserResDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userResDo) Debug() IUserResDo {
	return u.withDO(u.DO.Debug())
}

func (u userResDo) WithContext(ctx context.Context) IUserResDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userResDo) ReadDB() IUserResDo {
	return u.Clauses(dbresolver.Read)
}

func (u userResDo) WriteDB() IUserResDo {
	return u.Clauses(dbresolver.Write)
}

func (u userResDo) Session(config *gorm.Session) IUserResDo {
	return u.withDO(u.DO.Session(config))
}

func (u userResDo) Clauses(conds ...clause.Expression) IUserResDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userResDo) Returning(value interface{}, columns ...string) IUserResDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userResDo) Not(conds ...gen.Condition) IUserResDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userResDo) Or(conds ...gen.Condition) IUserResDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userResDo) Select(conds ...field.Expr) IUserResDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userResDo) Where(conds ...gen.Condition) IUserResDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userResDo) Order(conds ...field.Expr) IUserResDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userResDo) Distinct(cols ...field.Expr) IUserResDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userResDo) Omit(cols ...field.Expr) IUserResDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userResDo) Join(table schema.Tabler, on ...field.Expr) IUserResDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userResDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserResDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userResDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserResDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userResDo) Group(cols ...field.Expr) IUserResDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userResDo) Having(conds ...gen.Condition) IUserResDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userResDo) Limit(limit int) IUserResDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userResDo) Offset(offset int) IUserResDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userResDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserResDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userResDo) Unscoped() IUserResDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userResDo) Create(values ...*model.UserRes) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userResDo) CreateInBatches(values []*model.UserRes, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userResDo) Save(values ...*model.UserRes) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userResDo) First() (*model.UserRes, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserRes), nil
	}
}

func (u userResDo) Take() (*model.UserRes, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserRes), nil
	}
}

func (u userResDo) Last() (*model.UserRes, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserRes), nil
	}
}

func (u userResDo) Find() ([]*model.UserRes, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserRes), err
}

func (u userResDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserRes, err error) {
	buf := make([]*model.UserRes, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userResDo) FindInBatches(result *[]*model.UserRes, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userResDo) Attrs(attrs ...field.AssignExpr) IUserResDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userResDo) Assign(attrs ...field.AssignExpr) IUserResDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userResDo) Joins(fields ...field.RelationField) IUserResDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userResDo) Preload(fields ...field.RelationField) IUserResDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userResDo) FirstOrInit() (*model.UserRes, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserRes), nil
	}
}

func (u userResDo) FirstOrCreate() (*model.UserRes, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserRes), nil
	}
}

func (u userResDo) FindByPage(offset int, limit int) (result []*model.UserRes, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userResDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userResDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userResDo) Delete(models ...*model.UserRes) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userResDo) withDO(do gen.Dao) *userResDo {
	u.DO = *do.(*gen.DO)
	return u
}
