// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"server_go/dao/model"
)

func newUserData(db *gorm.DB, opts ...gen.DOOption) userData {
	_userData := userData{}

	_userData.userDataDo.UseDB(db, opts...)
	_userData.userDataDo.UseModel(&model.UserData{})

	tableName := _userData.userDataDo.TableName()
	_userData.ALL = field.NewAsterisk(tableName)
	_userData.UID = field.NewInt32(tableName, "uid")
	_userData.Key = field.NewString(tableName, "key")
	_userData.Value = field.NewString(tableName, "value")

	_userData.fillFieldMap()

	return _userData
}

type userData struct {
	userDataDo

	ALL   field.Asterisk
	UID   field.Int32
	Key   field.String
	Value field.String

	fieldMap map[string]field.Expr
}

func (u userData) Table(newTableName string) *userData {
	u.userDataDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userData) As(alias string) *userData {
	u.userDataDo.DO = *(u.userDataDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userData) updateTableName(table string) *userData {
	u.ALL = field.NewAsterisk(table)
	u.UID = field.NewInt32(table, "uid")
	u.Key = field.NewString(table, "key")
	u.Value = field.NewString(table, "value")

	u.fillFieldMap()

	return u
}

func (u *userData) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userData) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 3)
	u.fieldMap["uid"] = u.UID
	u.fieldMap["key"] = u.Key
	u.fieldMap["value"] = u.Value
}

func (u userData) clone(db *gorm.DB) userData {
	u.userDataDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userData) replaceDB(db *gorm.DB) userData {
	u.userDataDo.ReplaceDB(db)
	return u
}

type userDataDo struct{ gen.DO }

type IUserDataDo interface {
	gen.SubQuery
	Debug() IUserDataDo
	WithContext(ctx context.Context) IUserDataDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserDataDo
	WriteDB() IUserDataDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserDataDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserDataDo
	Not(conds ...gen.Condition) IUserDataDo
	Or(conds ...gen.Condition) IUserDataDo
	Select(conds ...field.Expr) IUserDataDo
	Where(conds ...gen.Condition) IUserDataDo
	Order(conds ...field.Expr) IUserDataDo
	Distinct(cols ...field.Expr) IUserDataDo
	Omit(cols ...field.Expr) IUserDataDo
	Join(table schema.Tabler, on ...field.Expr) IUserDataDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserDataDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserDataDo
	Group(cols ...field.Expr) IUserDataDo
	Having(conds ...gen.Condition) IUserDataDo
	Limit(limit int) IUserDataDo
	Offset(offset int) IUserDataDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserDataDo
	Unscoped() IUserDataDo
	Create(values ...*model.UserData) error
	CreateInBatches(values []*model.UserData, batchSize int) error
	Save(values ...*model.UserData) error
	First() (*model.UserData, error)
	Take() (*model.UserData, error)
	Last() (*model.UserData, error)
	Find() ([]*model.UserData, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserData, err error)
	FindInBatches(result *[]*model.UserData, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.UserData) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserDataDo
	Assign(attrs ...field.AssignExpr) IUserDataDo
	Joins(fields ...field.RelationField) IUserDataDo
	Preload(fields ...field.RelationField) IUserDataDo
	FirstOrInit() (*model.UserData, error)
	FirstOrCreate() (*model.UserData, error)
	FindByPage(offset int, limit int) (result []*model.UserData, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserDataDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userDataDo) Debug() IUserDataDo {
	return u.withDO(u.DO.Debug())
}

func (u userDataDo) WithContext(ctx context.Context) IUserDataDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userDataDo) ReadDB() IUserDataDo {
	return u.Clauses(dbresolver.Read)
}

func (u userDataDo) WriteDB() IUserDataDo {
	return u.Clauses(dbresolver.Write)
}

func (u userDataDo) Session(config *gorm.Session) IUserDataDo {
	return u.withDO(u.DO.Session(config))
}

func (u userDataDo) Clauses(conds ...clause.Expression) IUserDataDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userDataDo) Returning(value interface{}, columns ...string) IUserDataDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userDataDo) Not(conds ...gen.Condition) IUserDataDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userDataDo) Or(conds ...gen.Condition) IUserDataDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userDataDo) Select(conds ...field.Expr) IUserDataDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userDataDo) Where(conds ...gen.Condition) IUserDataDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userDataDo) Order(conds ...field.Expr) IUserDataDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userDataDo) Distinct(cols ...field.Expr) IUserDataDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userDataDo) Omit(cols ...field.Expr) IUserDataDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userDataDo) Join(table schema.Tabler, on ...field.Expr) IUserDataDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userDataDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserDataDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userDataDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserDataDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userDataDo) Group(cols ...field.Expr) IUserDataDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userDataDo) Having(conds ...gen.Condition) IUserDataDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userDataDo) Limit(limit int) IUserDataDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userDataDo) Offset(offset int) IUserDataDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userDataDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserDataDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userDataDo) Unscoped() IUserDataDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userDataDo) Create(values ...*model.UserData) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userDataDo) CreateInBatches(values []*model.UserData, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userDataDo) Save(values ...*model.UserData) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userDataDo) First() (*model.UserData, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserData), nil
	}
}

func (u userDataDo) Take() (*model.UserData, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserData), nil
	}
}

func (u userDataDo) Last() (*model.UserData, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserData), nil
	}
}

func (u userDataDo) Find() ([]*model.UserData, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserData), err
}

func (u userDataDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserData, err error) {
	buf := make([]*model.UserData, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userDataDo) FindInBatches(result *[]*model.UserData, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userDataDo) Attrs(attrs ...field.AssignExpr) IUserDataDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userDataDo) Assign(attrs ...field.AssignExpr) IUserDataDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userDataDo) Joins(fields ...field.RelationField) IUserDataDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userDataDo) Preload(fields ...field.RelationField) IUserDataDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userDataDo) FirstOrInit() (*model.UserData, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserData), nil
	}
}

func (u userDataDo) FirstOrCreate() (*model.UserData, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserData), nil
	}
}

func (u userDataDo) FindByPage(offset int, limit int) (result []*model.UserData, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userDataDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userDataDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userDataDo) Delete(models ...*model.UserData) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userDataDo) withDO(do gen.Dao) *userDataDo {
	u.DO = *do.(*gen.DO)
	return u
}
