// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"server_go/dao/model"
)

func newUserLoginkey(db *gorm.DB, opts ...gen.DOOption) userLoginkey {
	_userLoginkey := userLoginkey{}

	_userLoginkey.userLoginkeyDo.UseDB(db, opts...)
	_userLoginkey.userLoginkeyDo.UseModel(&model.UserLoginkey{})

	tableName := _userLoginkey.userLoginkeyDo.TableName()
	_userLoginkey.ALL = field.NewAsterisk(tableName)
	_userLoginkey.UID = field.NewInt64(tableName, "uid")
	_userLoginkey.Key = field.NewString(tableName, "key")
	_userLoginkey.Ver = field.NewInt32(tableName, "ver")
	_userLoginkey.Time = field.NewInt32(tableName, "time")

	_userLoginkey.fillFieldMap()

	return _userLoginkey
}

type userLoginkey struct {
	userLoginkeyDo

	ALL  field.Asterisk
	UID  field.Int64
	Key  field.String
	Ver  field.Int32 // 客户端版本号
	Time field.Int32 // 登录时间

	fieldMap map[string]field.Expr
}

func (u userLoginkey) Table(newTableName string) *userLoginkey {
	u.userLoginkeyDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userLoginkey) As(alias string) *userLoginkey {
	u.userLoginkeyDo.DO = *(u.userLoginkeyDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userLoginkey) updateTableName(table string) *userLoginkey {
	u.ALL = field.NewAsterisk(table)
	u.UID = field.NewInt64(table, "uid")
	u.Key = field.NewString(table, "key")
	u.Ver = field.NewInt32(table, "ver")
	u.Time = field.NewInt32(table, "time")

	u.fillFieldMap()

	return u
}

func (u *userLoginkey) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userLoginkey) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 4)
	u.fieldMap["uid"] = u.UID
	u.fieldMap["key"] = u.Key
	u.fieldMap["ver"] = u.Ver
	u.fieldMap["time"] = u.Time
}

func (u userLoginkey) clone(db *gorm.DB) userLoginkey {
	u.userLoginkeyDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userLoginkey) replaceDB(db *gorm.DB) userLoginkey {
	u.userLoginkeyDo.ReplaceDB(db)
	return u
}

type userLoginkeyDo struct{ gen.DO }

type IUserLoginkeyDo interface {
	gen.SubQuery
	Debug() IUserLoginkeyDo
	WithContext(ctx context.Context) IUserLoginkeyDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserLoginkeyDo
	WriteDB() IUserLoginkeyDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserLoginkeyDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserLoginkeyDo
	Not(conds ...gen.Condition) IUserLoginkeyDo
	Or(conds ...gen.Condition) IUserLoginkeyDo
	Select(conds ...field.Expr) IUserLoginkeyDo
	Where(conds ...gen.Condition) IUserLoginkeyDo
	Order(conds ...field.Expr) IUserLoginkeyDo
	Distinct(cols ...field.Expr) IUserLoginkeyDo
	Omit(cols ...field.Expr) IUserLoginkeyDo
	Join(table schema.Tabler, on ...field.Expr) IUserLoginkeyDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserLoginkeyDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserLoginkeyDo
	Group(cols ...field.Expr) IUserLoginkeyDo
	Having(conds ...gen.Condition) IUserLoginkeyDo
	Limit(limit int) IUserLoginkeyDo
	Offset(offset int) IUserLoginkeyDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserLoginkeyDo
	Unscoped() IUserLoginkeyDo
	Create(values ...*model.UserLoginkey) error
	CreateInBatches(values []*model.UserLoginkey, batchSize int) error
	Save(values ...*model.UserLoginkey) error
	First() (*model.UserLoginkey, error)
	Take() (*model.UserLoginkey, error)
	Last() (*model.UserLoginkey, error)
	Find() ([]*model.UserLoginkey, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserLoginkey, err error)
	FindInBatches(result *[]*model.UserLoginkey, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.UserLoginkey) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserLoginkeyDo
	Assign(attrs ...field.AssignExpr) IUserLoginkeyDo
	Joins(fields ...field.RelationField) IUserLoginkeyDo
	Preload(fields ...field.RelationField) IUserLoginkeyDo
	FirstOrInit() (*model.UserLoginkey, error)
	FirstOrCreate() (*model.UserLoginkey, error)
	FindByPage(offset int, limit int) (result []*model.UserLoginkey, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserLoginkeyDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userLoginkeyDo) Debug() IUserLoginkeyDo {
	return u.withDO(u.DO.Debug())
}

func (u userLoginkeyDo) WithContext(ctx context.Context) IUserLoginkeyDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userLoginkeyDo) ReadDB() IUserLoginkeyDo {
	return u.Clauses(dbresolver.Read)
}

func (u userLoginkeyDo) WriteDB() IUserLoginkeyDo {
	return u.Clauses(dbresolver.Write)
}

func (u userLoginkeyDo) Session(config *gorm.Session) IUserLoginkeyDo {
	return u.withDO(u.DO.Session(config))
}

func (u userLoginkeyDo) Clauses(conds ...clause.Expression) IUserLoginkeyDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userLoginkeyDo) Returning(value interface{}, columns ...string) IUserLoginkeyDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userLoginkeyDo) Not(conds ...gen.Condition) IUserLoginkeyDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userLoginkeyDo) Or(conds ...gen.Condition) IUserLoginkeyDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userLoginkeyDo) Select(conds ...field.Expr) IUserLoginkeyDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userLoginkeyDo) Where(conds ...gen.Condition) IUserLoginkeyDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userLoginkeyDo) Order(conds ...field.Expr) IUserLoginkeyDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userLoginkeyDo) Distinct(cols ...field.Expr) IUserLoginkeyDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userLoginkeyDo) Omit(cols ...field.Expr) IUserLoginkeyDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userLoginkeyDo) Join(table schema.Tabler, on ...field.Expr) IUserLoginkeyDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userLoginkeyDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserLoginkeyDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userLoginkeyDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserLoginkeyDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userLoginkeyDo) Group(cols ...field.Expr) IUserLoginkeyDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userLoginkeyDo) Having(conds ...gen.Condition) IUserLoginkeyDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userLoginkeyDo) Limit(limit int) IUserLoginkeyDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userLoginkeyDo) Offset(offset int) IUserLoginkeyDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userLoginkeyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserLoginkeyDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userLoginkeyDo) Unscoped() IUserLoginkeyDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userLoginkeyDo) Create(values ...*model.UserLoginkey) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userLoginkeyDo) CreateInBatches(values []*model.UserLoginkey, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userLoginkeyDo) Save(values ...*model.UserLoginkey) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userLoginkeyDo) First() (*model.UserLoginkey, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserLoginkey), nil
	}
}

func (u userLoginkeyDo) Take() (*model.UserLoginkey, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserLoginkey), nil
	}
}

func (u userLoginkeyDo) Last() (*model.UserLoginkey, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserLoginkey), nil
	}
}

func (u userLoginkeyDo) Find() ([]*model.UserLoginkey, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserLoginkey), err
}

func (u userLoginkeyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserLoginkey, err error) {
	buf := make([]*model.UserLoginkey, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userLoginkeyDo) FindInBatches(result *[]*model.UserLoginkey, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userLoginkeyDo) Attrs(attrs ...field.AssignExpr) IUserLoginkeyDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userLoginkeyDo) Assign(attrs ...field.AssignExpr) IUserLoginkeyDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userLoginkeyDo) Joins(fields ...field.RelationField) IUserLoginkeyDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userLoginkeyDo) Preload(fields ...field.RelationField) IUserLoginkeyDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userLoginkeyDo) FirstOrInit() (*model.UserLoginkey, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserLoginkey), nil
	}
}

func (u userLoginkeyDo) FirstOrCreate() (*model.UserLoginkey, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserLoginkey), nil
	}
}

func (u userLoginkeyDo) FindByPage(offset int, limit int) (result []*model.UserLoginkey, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userLoginkeyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userLoginkeyDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userLoginkeyDo) Delete(models ...*model.UserLoginkey) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userLoginkeyDo) withDO(do gen.Dao) *userLoginkeyDo {
	u.DO = *do.(*gen.DO)
	return u
}
