// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"server_go/dao/model"
)

func newUserItem(db *gorm.DB, opts ...gen.DOOption) userItem {
	_userItem := userItem{}

	_userItem.userItemDo.UseDB(db, opts...)
	_userItem.userItemDo.UseModel(&model.UserItem{})

	tableName := _userItem.userItemDo.TableName()
	_userItem.ALL = field.NewAsterisk(tableName)
	_userItem.UID = field.NewInt64(tableName, "uid")
	_userItem.Tid = field.NewInt32(tableName, "tid")
	_userItem.Cnt = field.NewInt32(tableName, "cnt")

	_userItem.fillFieldMap()

	return _userItem
}

type userItem struct {
	userItemDo

	ALL field.Asterisk
	UID field.Int64
	Tid field.Int32
	Cnt field.Int32

	fieldMap map[string]field.Expr
}

func (u userItem) Table(newTableName string) *userItem {
	u.userItemDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userItem) As(alias string) *userItem {
	u.userItemDo.DO = *(u.userItemDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userItem) updateTableName(table string) *userItem {
	u.ALL = field.NewAsterisk(table)
	u.UID = field.NewInt64(table, "uid")
	u.Tid = field.NewInt32(table, "tid")
	u.Cnt = field.NewInt32(table, "cnt")

	u.fillFieldMap()

	return u
}

func (u *userItem) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userItem) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 3)
	u.fieldMap["uid"] = u.UID
	u.fieldMap["tid"] = u.Tid
	u.fieldMap["cnt"] = u.Cnt
}

func (u userItem) clone(db *gorm.DB) userItem {
	u.userItemDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userItem) replaceDB(db *gorm.DB) userItem {
	u.userItemDo.ReplaceDB(db)
	return u
}

type userItemDo struct{ gen.DO }

type IUserItemDo interface {
	gen.SubQuery
	Debug() IUserItemDo
	WithContext(ctx context.Context) IUserItemDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserItemDo
	WriteDB() IUserItemDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserItemDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserItemDo
	Not(conds ...gen.Condition) IUserItemDo
	Or(conds ...gen.Condition) IUserItemDo
	Select(conds ...field.Expr) IUserItemDo
	Where(conds ...gen.Condition) IUserItemDo
	Order(conds ...field.Expr) IUserItemDo
	Distinct(cols ...field.Expr) IUserItemDo
	Omit(cols ...field.Expr) IUserItemDo
	Join(table schema.Tabler, on ...field.Expr) IUserItemDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserItemDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserItemDo
	Group(cols ...field.Expr) IUserItemDo
	Having(conds ...gen.Condition) IUserItemDo
	Limit(limit int) IUserItemDo
	Offset(offset int) IUserItemDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserItemDo
	Unscoped() IUserItemDo
	Create(values ...*model.UserItem) error
	CreateInBatches(values []*model.UserItem, batchSize int) error
	Save(values ...*model.UserItem) error
	First() (*model.UserItem, error)
	Take() (*model.UserItem, error)
	Last() (*model.UserItem, error)
	Find() ([]*model.UserItem, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserItem, err error)
	FindInBatches(result *[]*model.UserItem, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.UserItem) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserItemDo
	Assign(attrs ...field.AssignExpr) IUserItemDo
	Joins(fields ...field.RelationField) IUserItemDo
	Preload(fields ...field.RelationField) IUserItemDo
	FirstOrInit() (*model.UserItem, error)
	FirstOrCreate() (*model.UserItem, error)
	FindByPage(offset int, limit int) (result []*model.UserItem, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserItemDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userItemDo) Debug() IUserItemDo {
	return u.withDO(u.DO.Debug())
}

func (u userItemDo) WithContext(ctx context.Context) IUserItemDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userItemDo) ReadDB() IUserItemDo {
	return u.Clauses(dbresolver.Read)
}

func (u userItemDo) WriteDB() IUserItemDo {
	return u.Clauses(dbresolver.Write)
}

func (u userItemDo) Session(config *gorm.Session) IUserItemDo {
	return u.withDO(u.DO.Session(config))
}

func (u userItemDo) Clauses(conds ...clause.Expression) IUserItemDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userItemDo) Returning(value interface{}, columns ...string) IUserItemDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userItemDo) Not(conds ...gen.Condition) IUserItemDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userItemDo) Or(conds ...gen.Condition) IUserItemDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userItemDo) Select(conds ...field.Expr) IUserItemDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userItemDo) Where(conds ...gen.Condition) IUserItemDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userItemDo) Order(conds ...field.Expr) IUserItemDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userItemDo) Distinct(cols ...field.Expr) IUserItemDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userItemDo) Omit(cols ...field.Expr) IUserItemDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userItemDo) Join(table schema.Tabler, on ...field.Expr) IUserItemDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userItemDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserItemDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userItemDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserItemDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userItemDo) Group(cols ...field.Expr) IUserItemDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userItemDo) Having(conds ...gen.Condition) IUserItemDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userItemDo) Limit(limit int) IUserItemDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userItemDo) Offset(offset int) IUserItemDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userItemDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserItemDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userItemDo) Unscoped() IUserItemDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userItemDo) Create(values ...*model.UserItem) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userItemDo) CreateInBatches(values []*model.UserItem, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userItemDo) Save(values ...*model.UserItem) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userItemDo) First() (*model.UserItem, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserItem), nil
	}
}

func (u userItemDo) Take() (*model.UserItem, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserItem), nil
	}
}

func (u userItemDo) Last() (*model.UserItem, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserItem), nil
	}
}

func (u userItemDo) Find() ([]*model.UserItem, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserItem), err
}

func (u userItemDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserItem, err error) {
	buf := make([]*model.UserItem, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userItemDo) FindInBatches(result *[]*model.UserItem, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userItemDo) Attrs(attrs ...field.AssignExpr) IUserItemDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userItemDo) Assign(attrs ...field.AssignExpr) IUserItemDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userItemDo) Joins(fields ...field.RelationField) IUserItemDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userItemDo) Preload(fields ...field.RelationField) IUserItemDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userItemDo) FirstOrInit() (*model.UserItem, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserItem), nil
	}
}

func (u userItemDo) FirstOrCreate() (*model.UserItem, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserItem), nil
	}
}

func (u userItemDo) FindByPage(offset int, limit int) (result []*model.UserItem, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userItemDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userItemDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userItemDo) Delete(models ...*model.UserItem) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userItemDo) withDO(do gen.Dao) *userItemDo {
	u.DO = *do.(*gen.DO)
	return u
}
