// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"server_gin/dao/model"
)

func newUserBag(db *gorm.DB, opts ...gen.DOOption) userBag {
	_userBag := userBag{}

	_userBag.userBagDo.UseDB(db, opts...)
	_userBag.userBagDo.UseModel(&model.UserBag{})

	tableName := _userBag.userBagDo.TableName()
	_userBag.ALL = field.NewAsterisk(tableName)
	_userBag.ID = field.NewInt64(tableName, "id")
	_userBag.UID = field.NewInt32(tableName, "uid")
	_userBag.Chapter = field.NewInt32(tableName, "chapter")
	_userBag.Time = field.NewInt32(tableName, "time")
	_userBag.Itemid = field.NewInt32(tableName, "itemid")
	_userBag.Info = field.NewString(tableName, "info")
	_userBag.Type = field.NewInt32(tableName, "type")

	_userBag.fillFieldMap()

	return _userBag
}

// userBag 用户的包裹
type userBag struct {
	userBagDo

	ALL     field.Asterisk
	ID      field.Int64
	UID     field.Int32
	Chapter field.Int32  // 副本id - 0-主格子
	Time    field.Int32  // 操作更新时间
	Itemid  field.Int32  // 物品id, 0=空
	Info    field.String // 格子信息
	Type    field.Int32  // 格子类型,0-普通,1-道具购买

	fieldMap map[string]field.Expr
}

func (u userBag) Table(newTableName string) *userBag {
	u.userBagDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userBag) As(alias string) *userBag {
	u.userBagDo.DO = *(u.userBagDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userBag) updateTableName(table string) *userBag {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt64(table, "id")
	u.UID = field.NewInt32(table, "uid")
	u.Chapter = field.NewInt32(table, "chapter")
	u.Time = field.NewInt32(table, "time")
	u.Itemid = field.NewInt32(table, "itemid")
	u.Info = field.NewString(table, "info")
	u.Type = field.NewInt32(table, "type")

	u.fillFieldMap()

	return u
}

func (u *userBag) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userBag) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 7)
	u.fieldMap["id"] = u.ID
	u.fieldMap["uid"] = u.UID
	u.fieldMap["chapter"] = u.Chapter
	u.fieldMap["time"] = u.Time
	u.fieldMap["itemid"] = u.Itemid
	u.fieldMap["info"] = u.Info
	u.fieldMap["type"] = u.Type
}

func (u userBag) clone(db *gorm.DB) userBag {
	u.userBagDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userBag) replaceDB(db *gorm.DB) userBag {
	u.userBagDo.ReplaceDB(db)
	return u
}

type userBagDo struct{ gen.DO }

type IUserBagDo interface {
	gen.SubQuery
	Debug() IUserBagDo
	WithContext(ctx context.Context) IUserBagDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserBagDo
	WriteDB() IUserBagDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserBagDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserBagDo
	Not(conds ...gen.Condition) IUserBagDo
	Or(conds ...gen.Condition) IUserBagDo
	Select(conds ...field.Expr) IUserBagDo
	Where(conds ...gen.Condition) IUserBagDo
	Order(conds ...field.Expr) IUserBagDo
	Distinct(cols ...field.Expr) IUserBagDo
	Omit(cols ...field.Expr) IUserBagDo
	Join(table schema.Tabler, on ...field.Expr) IUserBagDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserBagDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserBagDo
	Group(cols ...field.Expr) IUserBagDo
	Having(conds ...gen.Condition) IUserBagDo
	Limit(limit int) IUserBagDo
	Offset(offset int) IUserBagDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserBagDo
	Unscoped() IUserBagDo
	Create(values ...*model.UserBag) error
	CreateInBatches(values []*model.UserBag, batchSize int) error
	Save(values ...*model.UserBag) error
	First() (*model.UserBag, error)
	Take() (*model.UserBag, error)
	Last() (*model.UserBag, error)
	Find() ([]*model.UserBag, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserBag, err error)
	FindInBatches(result *[]*model.UserBag, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.UserBag) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserBagDo
	Assign(attrs ...field.AssignExpr) IUserBagDo
	Joins(fields ...field.RelationField) IUserBagDo
	Preload(fields ...field.RelationField) IUserBagDo
	FirstOrInit() (*model.UserBag, error)
	FirstOrCreate() (*model.UserBag, error)
	FindByPage(offset int, limit int) (result []*model.UserBag, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserBagDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userBagDo) Debug() IUserBagDo {
	return u.withDO(u.DO.Debug())
}

func (u userBagDo) WithContext(ctx context.Context) IUserBagDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userBagDo) ReadDB() IUserBagDo {
	return u.Clauses(dbresolver.Read)
}

func (u userBagDo) WriteDB() IUserBagDo {
	return u.Clauses(dbresolver.Write)
}

func (u userBagDo) Session(config *gorm.Session) IUserBagDo {
	return u.withDO(u.DO.Session(config))
}

func (u userBagDo) Clauses(conds ...clause.Expression) IUserBagDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userBagDo) Returning(value interface{}, columns ...string) IUserBagDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userBagDo) Not(conds ...gen.Condition) IUserBagDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userBagDo) Or(conds ...gen.Condition) IUserBagDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userBagDo) Select(conds ...field.Expr) IUserBagDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userBagDo) Where(conds ...gen.Condition) IUserBagDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userBagDo) Order(conds ...field.Expr) IUserBagDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userBagDo) Distinct(cols ...field.Expr) IUserBagDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userBagDo) Omit(cols ...field.Expr) IUserBagDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userBagDo) Join(table schema.Tabler, on ...field.Expr) IUserBagDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userBagDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserBagDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userBagDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserBagDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userBagDo) Group(cols ...field.Expr) IUserBagDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userBagDo) Having(conds ...gen.Condition) IUserBagDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userBagDo) Limit(limit int) IUserBagDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userBagDo) Offset(offset int) IUserBagDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userBagDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserBagDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userBagDo) Unscoped() IUserBagDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userBagDo) Create(values ...*model.UserBag) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userBagDo) CreateInBatches(values []*model.UserBag, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userBagDo) Save(values ...*model.UserBag) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userBagDo) First() (*model.UserBag, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserBag), nil
	}
}

func (u userBagDo) Take() (*model.UserBag, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserBag), nil
	}
}

func (u userBagDo) Last() (*model.UserBag, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserBag), nil
	}
}

func (u userBagDo) Find() ([]*model.UserBag, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserBag), err
}

func (u userBagDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserBag, err error) {
	buf := make([]*model.UserBag, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userBagDo) FindInBatches(result *[]*model.UserBag, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userBagDo) Attrs(attrs ...field.AssignExpr) IUserBagDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userBagDo) Assign(attrs ...field.AssignExpr) IUserBagDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userBagDo) Joins(fields ...field.RelationField) IUserBagDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userBagDo) Preload(fields ...field.RelationField) IUserBagDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userBagDo) FirstOrInit() (*model.UserBag, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserBag), nil
	}
}

func (u userBagDo) FirstOrCreate() (*model.UserBag, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserBag), nil
	}
}

func (u userBagDo) FindByPage(offset int, limit int) (result []*model.UserBag, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userBagDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userBagDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userBagDo) Delete(models ...*model.UserBag) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userBagDo) withDO(do gen.Dao) *userBagDo {
	u.DO = *do.(*gen.DO)
	return u
}
