// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"server_go/dao/model"
)

func newUserBagTp(db *gorm.DB, opts ...gen.DOOption) userBagTp {
	_userBagTp := userBagTp{}

	_userBagTp.userBagTpDo.UseDB(db, opts...)
	_userBagTp.userBagTpDo.UseModel(&model.UserBagTp{})

	tableName := _userBagTp.userBagTpDo.TableName()
	_userBagTp.ALL = field.NewAsterisk(tableName)
	_userBagTp.ID = field.NewInt64(tableName, "id")
	_userBagTp.UID = field.NewInt32(tableName, "uid")
	_userBagTp.Chapter = field.NewInt32(tableName, "chapter")
	_userBagTp.Time = field.NewInt32(tableName, "time")
	_userBagTp.Itemid = field.NewInt32(tableName, "itemid")
	_userBagTp.Count_ = field.NewInt32(tableName, "count")

	_userBagTp.fillFieldMap()

	return _userBagTp
}

// userBagTp 用户临时包裹
type userBagTp struct {
	userBagTpDo

	ALL     field.Asterisk
	ID      field.Int64
	UID     field.Int32
	Chapter field.Int32 // 副本id - 0 主线
	Time    field.Int32 // 更新时间
	Itemid  field.Int32 // 物品id, 0=空
	Count_  field.Int32 // 道具数量

	fieldMap map[string]field.Expr
}

func (u userBagTp) Table(newTableName string) *userBagTp {
	u.userBagTpDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userBagTp) As(alias string) *userBagTp {
	u.userBagTpDo.DO = *(u.userBagTpDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userBagTp) updateTableName(table string) *userBagTp {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt64(table, "id")
	u.UID = field.NewInt32(table, "uid")
	u.Chapter = field.NewInt32(table, "chapter")
	u.Time = field.NewInt32(table, "time")
	u.Itemid = field.NewInt32(table, "itemid")
	u.Count_ = field.NewInt32(table, "count")

	u.fillFieldMap()

	return u
}

func (u *userBagTp) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userBagTp) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 6)
	u.fieldMap["id"] = u.ID
	u.fieldMap["uid"] = u.UID
	u.fieldMap["chapter"] = u.Chapter
	u.fieldMap["time"] = u.Time
	u.fieldMap["itemid"] = u.Itemid
	u.fieldMap["count"] = u.Count_
}

func (u userBagTp) clone(db *gorm.DB) userBagTp {
	u.userBagTpDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userBagTp) replaceDB(db *gorm.DB) userBagTp {
	u.userBagTpDo.ReplaceDB(db)
	return u
}

type userBagTpDo struct{ gen.DO }

type IUserBagTpDo interface {
	gen.SubQuery
	Debug() IUserBagTpDo
	WithContext(ctx context.Context) IUserBagTpDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserBagTpDo
	WriteDB() IUserBagTpDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserBagTpDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserBagTpDo
	Not(conds ...gen.Condition) IUserBagTpDo
	Or(conds ...gen.Condition) IUserBagTpDo
	Select(conds ...field.Expr) IUserBagTpDo
	Where(conds ...gen.Condition) IUserBagTpDo
	Order(conds ...field.Expr) IUserBagTpDo
	Distinct(cols ...field.Expr) IUserBagTpDo
	Omit(cols ...field.Expr) IUserBagTpDo
	Join(table schema.Tabler, on ...field.Expr) IUserBagTpDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserBagTpDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserBagTpDo
	Group(cols ...field.Expr) IUserBagTpDo
	Having(conds ...gen.Condition) IUserBagTpDo
	Limit(limit int) IUserBagTpDo
	Offset(offset int) IUserBagTpDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserBagTpDo
	Unscoped() IUserBagTpDo
	Create(values ...*model.UserBagTp) error
	CreateInBatches(values []*model.UserBagTp, batchSize int) error
	Save(values ...*model.UserBagTp) error
	First() (*model.UserBagTp, error)
	Take() (*model.UserBagTp, error)
	Last() (*model.UserBagTp, error)
	Find() ([]*model.UserBagTp, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserBagTp, err error)
	FindInBatches(result *[]*model.UserBagTp, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.UserBagTp) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserBagTpDo
	Assign(attrs ...field.AssignExpr) IUserBagTpDo
	Joins(fields ...field.RelationField) IUserBagTpDo
	Preload(fields ...field.RelationField) IUserBagTpDo
	FirstOrInit() (*model.UserBagTp, error)
	FirstOrCreate() (*model.UserBagTp, error)
	FindByPage(offset int, limit int) (result []*model.UserBagTp, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserBagTpDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userBagTpDo) Debug() IUserBagTpDo {
	return u.withDO(u.DO.Debug())
}

func (u userBagTpDo) WithContext(ctx context.Context) IUserBagTpDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userBagTpDo) ReadDB() IUserBagTpDo {
	return u.Clauses(dbresolver.Read)
}

func (u userBagTpDo) WriteDB() IUserBagTpDo {
	return u.Clauses(dbresolver.Write)
}

func (u userBagTpDo) Session(config *gorm.Session) IUserBagTpDo {
	return u.withDO(u.DO.Session(config))
}

func (u userBagTpDo) Clauses(conds ...clause.Expression) IUserBagTpDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userBagTpDo) Returning(value interface{}, columns ...string) IUserBagTpDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userBagTpDo) Not(conds ...gen.Condition) IUserBagTpDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userBagTpDo) Or(conds ...gen.Condition) IUserBagTpDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userBagTpDo) Select(conds ...field.Expr) IUserBagTpDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userBagTpDo) Where(conds ...gen.Condition) IUserBagTpDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userBagTpDo) Order(conds ...field.Expr) IUserBagTpDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userBagTpDo) Distinct(cols ...field.Expr) IUserBagTpDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userBagTpDo) Omit(cols ...field.Expr) IUserBagTpDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userBagTpDo) Join(table schema.Tabler, on ...field.Expr) IUserBagTpDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userBagTpDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserBagTpDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userBagTpDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserBagTpDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userBagTpDo) Group(cols ...field.Expr) IUserBagTpDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userBagTpDo) Having(conds ...gen.Condition) IUserBagTpDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userBagTpDo) Limit(limit int) IUserBagTpDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userBagTpDo) Offset(offset int) IUserBagTpDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userBagTpDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserBagTpDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userBagTpDo) Unscoped() IUserBagTpDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userBagTpDo) Create(values ...*model.UserBagTp) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userBagTpDo) CreateInBatches(values []*model.UserBagTp, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userBagTpDo) Save(values ...*model.UserBagTp) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userBagTpDo) First() (*model.UserBagTp, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserBagTp), nil
	}
}

func (u userBagTpDo) Take() (*model.UserBagTp, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserBagTp), nil
	}
}

func (u userBagTpDo) Last() (*model.UserBagTp, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserBagTp), nil
	}
}

func (u userBagTpDo) Find() ([]*model.UserBagTp, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserBagTp), err
}

func (u userBagTpDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserBagTp, err error) {
	buf := make([]*model.UserBagTp, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userBagTpDo) FindInBatches(result *[]*model.UserBagTp, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userBagTpDo) Attrs(attrs ...field.AssignExpr) IUserBagTpDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userBagTpDo) Assign(attrs ...field.AssignExpr) IUserBagTpDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userBagTpDo) Joins(fields ...field.RelationField) IUserBagTpDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userBagTpDo) Preload(fields ...field.RelationField) IUserBagTpDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userBagTpDo) FirstOrInit() (*model.UserBagTp, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserBagTp), nil
	}
}

func (u userBagTpDo) FirstOrCreate() (*model.UserBagTp, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserBagTp), nil
	}
}

func (u userBagTpDo) FindByPage(offset int, limit int) (result []*model.UserBagTp, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userBagTpDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userBagTpDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userBagTpDo) Delete(models ...*model.UserBagTp) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userBagTpDo) withDO(do gen.Dao) *userBagTpDo {
	u.DO = *do.(*gen.DO)
	return u
}
