// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package bag

import (
	"server_go/api/bag"
)

type ControllerV1 struct{}

func NewV1() bag.IBagV1 {
	return &ControllerV1{}
}
