// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMemConfig = "mem_config"

// MemConfig mapped from table <mem_config>
type MemConfig struct {
	ID    int32  `gorm:"column:id;type:int;primaryKey" json:"id"`
	Value string `gorm:"column:value;type:text" json:"value"`
	Tips  string `gorm:"column:tips;type:varchar(255)" json:"tips"`
}

// TableName MemConfig's table name
func (*MemConfig) TableName() string {
	return TableNameMemConfig
}
