// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePrfItem = "prf_item"

// PrfItem mapped from table <prf_item>
type PrfItem struct {
	ID  int32 `gorm:"column:id;type:int;primaryKey" json:"id"`
	Ser int32 `gorm:"column:ser;type:int;index:t,priority:1;comment:道具系列" json:"ser"` // 道具系列
	/*
		道具类型
		0 普通道具
		1 工厂道具
		2 转换器
		3 点击使用的道具
		4 拖拽到目标使用的道具
	*/
	Type       int32  `gorm:"column:type;type:int;comment:道具类型\n0 普通道具\n1 工厂道具\n2 转换器\n3 点击使用的道具\n4 拖拽到目标使用的道具" json:"type"`
	Cost       int32  `gorm:"column:cost;type:int;comment:工厂类型道具产出消耗的体力" json:"cost"`                 // 工厂类型道具产出消耗的体力
	Lv         int32  `gorm:"column:lv;type:int;comment:道具等级" json:"lv"`                              // 道具等级
	From       string `gorm:"column:from;type:varchar(64);comment:来源id" json:"from"`                  // 来源id
	Name       string `gorm:"column:name;type:varchar(64);comment:道具名称" json:"name"`                  // 道具名称
	Tips       string `gorm:"column:tips;type:varchar(255);comment:道具介绍" json:"tips"`                 // 道具介绍
	Star       int32  `gorm:"column:star;type:int;index:s,priority:1;comment:该道具对应的绿星数量" json:"star"` // 该道具对应的绿星数量
	Next       int32  `gorm:"column:next;type:int;index:m,priority:1;comment:合成道具id" json:"next"`     // 合成道具id
	AutoDrop   int32  `gorm:"column:auto_drop;type:tinyint;comment:工厂是否自动产出道具" json:"auto_drop"`      // 工厂是否自动产出道具
	NeedOpen   int32  `gorm:"column:need_open;type:tinyint;comment:是否需要等待开启" json:"need_open"`        // 是否需要等待开启
	CoolDrop   int32  `gorm:"column:cool_drop;type:int;comment:一次CD掉落个数" json:"cool_drop"`            // 一次CD掉落个数
	CoolTime   int32  `gorm:"column:cool_time;type:int;comment:冷却时间" json:"cool_time"`                // 冷却时间
	CoolMaxnum int32  `gorm:"column:cool_maxnum;type:int;comment:冷却时间累积次数" json:"cool_maxnum"`        // 冷却时间累积次数
	CoolMoney  int32  `gorm:"column:cool_money;type:int;comment:冷却加速花费钻石（最大值）" json:"cool_money"`     // 冷却加速花费钻石（最大值）
	Sell       int32  `gorm:"column:sell;type:int;comment:出售价格-金币" json:"sell"`                       // 出售价格-金币
	Use        int32  `gorm:"column:use;type:int;comment:可直接使用的道具，boxid" json:"use"`                  // 可直接使用的道具，boxid
	/*
		特殊-掉落完后变成什么
		<0 直接消失
		==0 进入cd
		>0 变成指定道具, 如果道具不存在也消失
	*/
	Die   int32  `gorm:"column:die;type:int;comment:特殊-掉落完后变成什么\n<0 直接消失\n==0 进入cd\n>0 变成指定道具, 如果道具不存在也消失" json:"die"`
	Exp   int32  `gorm:"column:exp;type:int;comment:该等级道具合成下一级道具时是否会产出经验" json:"exp"`      // 该等级道具合成下一级道具时是否会产出经验
	Gold  int32  `gorm:"column:gold;type:int;comment:副本合成掉落金币" json:"gold"`                // 副本合成掉落金币
	Rare  int32  `gorm:"column:rare;type:int;comment:0=普通，1=稀有（出售时跳出提醒框）" json:"rare"`     // 0=普通，1=稀有（出售时跳出提醒框）
	Tids  string `gorm:"column:tids;type:varchar(64);comment:转换器内可投入物品的id" json:"tids"`    // 转换器内可投入物品的id
	Count string `gorm:"column:count;type:varchar(64);comment:转换器内对应投入物品的数量" json:"count"` // 转换器内对应投入物品的数量
}

// TableName PrfItem's table name
func (*PrfItem) TableName() string {
	return TableNamePrfItem
}
