// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePrfTask = "prf_task"

// PrfTask mapped from table <prf_task>
type PrfTask struct {
	ID        int32  `gorm:"column:id;type:int;primaryKey" json:"id"`
	Ser       int32  `gorm:"column:ser;type:int;index:tl,priority:1;comment:对应工厂的ser" json:"ser"` // 对应工厂的ser
	Tid       string `gorm:"column:tid;type:varchar(64);comment:任务道具id" json:"tid"`               // 任务道具id
	Npc       int32  `gorm:"column:npc;type:int" json:"npc"`
	StartLoop int32  `gorm:"column:start_loop;type:int;index:lp,priority:1;comment:开启循环的第一个任务有效,每组里如果都是0,不开启循环" json:"start_loop"` // 开启循环的第一个任务有效,每组里如果都是0,不开启循环
}

// TableName PrfTask's table name
func (*PrfTask) TableName() string {
	return TableNamePrfTask
}
