// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePrfFlower = "prf_flower"

// PrfFlower mapped from table <prf_flower>
type PrfFlower struct {
	ID   int32  `gorm:"column:id;type:int;primaryKey" json:"id"`
	Name string `gorm:"column:name;type:varchar(64);comment:花的名字" json:"name"` // 花的名字
	Des  string `gorm:"column:des;type:varchar(128);comment:花语" json:"des"`    // 花语
	/*
		0=升级解锁
		1=测试用
		2=活动获得
		3=鲜花礼包
		4=徐霞客处获得
		5=VIP专享
		6=公会获得
		7=敬请期待
		8=已绝版
	*/
	From                 int32  `gorm:"column:from;type:tinyint;index:from,priority:1;comment:0=升级解锁\n1=测试用\n2=活动获得\n3=鲜花礼包\n4=徐霞客处获得\n5=VIP专享\n6=公会获得\n7=敬请期待\n8=已绝版" json:"from"`
	FromTip              string `gorm:"column:from_tip;type:varchar(255);comment:来源提示" json:"from_tip"`                                       // 来源提示
	Index                int32  `gorm:"column:index;type:int;comment:排序" json:"index"`                                                        // 排序
	SellRes              string `gorm:"column:sell_res;type:varchar(128);comment:出售获得的资源，类型,id,数量" json:"sell_res"`                           // 出售获得的资源，类型,id,数量
	Water                int32  `gorm:"column:water;type:tinyint;comment:种植消耗的水滴" json:"water"`                                               // 种植消耗的水滴
	Cost                 string `gorm:"column:cost;type:varchar(64);comment:培育所需资源" json:"cost"`                                              // 培育所需资源
	Cd                   int32  `gorm:"column:cd;type:int;comment:培育所需时间" json:"cd"`                                                          // 培育所需时间
	Qua                  int32  `gorm:"column:qua;type:tinyint;index:qua,priority:1;comment:品质。1=绿色，2=蓝色，3=紫色，4=红色，5=金色" json:"qua"`          // 品质。1=绿色，2=蓝色，3=紫色，4=红色，5=金色
	Charm                int32  `gorm:"column:charm;type:tinyint;comment:魅力值" json:"charm"`                                                   // 魅力值
	Pic0                 string `gorm:"column:pic_0;type:varchar(64);comment:培育房-种子、收割-掉落的种子、鲜花升级-卡片种子" json:"pic_0"`                         // 培育房-种子、收割-掉落的种子、鲜花升级-卡片种子
	Pic1                 string `gorm:"column:pic_1;type:varchar(64);comment:种地-刚刚播种" json:"pic_1"`                                           // 种地-刚刚播种
	Pic2                 string `gorm:"column:pic_2;type:varchar(64);comment:种地-长了一半" json:"pic_2"`                                           // 种地-长了一半
	Pic3                 string `gorm:"column:pic_3;type:varchar(64);comment:种地-完全长成、徐霞客、社团种植花盆内" json:"pic_3"`                               // 种地-完全长成、徐霞客、社团种植花盆内
	Pic4                 string `gorm:"column:pic_4;type:varchar(64);comment:收割-掉在地上" json:"pic_4"`                                           // 收割-掉在地上
	Pic5                 string `gorm:"column:pic_5;type:varchar(64);comment:培育房-培育花台缩略图、仓库-缩略图、播种选择页、鲜花订单、插花、社团种植收取、好友交易、按住播种" json:"pic_5"` // 培育房-培育花台缩略图、仓库-缩略图、播种选择页、鲜花订单、插花、社团种植收取、好友交易、按住播种
	Pic6                 string `gorm:"column:pic_6;type:varchar(64);comment:花谱-外层显示、花市订单" json:"pic_6"`                                      // 花谱-外层显示、花市订单
	Pic7                 string `gorm:"column:pic_7;type:varchar(64);comment:花谱-带花瓶" json:"pic_7"`                                            // 花谱-带花瓶
	PicLand              string `gorm:"column:pic_land;type:varchar(64);comment:土地图片" json:"pic_land"`                                        // 土地图片
	SpineFlowerLand      string `gorm:"column:spine_flower_land;type:varchar(64);comment:种在地里的花动画" json:"spine_flower_land"`                  // 种在地里的花动画
	SpineLand            string `gorm:"column:spine_land;type:varchar(64);comment:地块动画" json:"spine_land"`                                    // 地块动画
	SpineFlowerBook      string `gorm:"column:spine_flower_book;type:varchar(64);comment:图鉴花动画" json:"spine_flower_book"`                     // 图鉴花动画
	SpineFlowerBookExtra string `gorm:"column:spine_flower_book_extra;type:varchar(64);comment:图鉴花动画-附加" json:"spine_flower_book_extra"`      // 图鉴花动画-附加
	NoBottle             int32  `gorm:"column:no_bottle;type:tinyint;comment:不显示瓶子" json:"no_bottle"`                                         // 不显示瓶子
}

// TableName PrfFlower's table name
func (*PrfFlower) TableName() string {
	return TableNamePrfFlower
}
