// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePrfRes = "prf_res"

// PrfRes 游戏资源定义汇总
type PrfRes struct {
	ID   int32  `gorm:"column:id;type:int;primaryKey;comment:资源ID" json:"id"`        // 资源ID
	Name string `gorm:"column:name;type:varchar(32);comment:资源名称" json:"name"`       // 资源名称
	Tips string `gorm:"column:tips;type:varchar(128);comment:资源说明,用法提示" json:"tips"` // 资源说明,用法提示
}

// TableName PrfRes's table name
func (*PrfRes) TableName() string {
	return TableNamePrfRes
}
