// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePrfFlowerLevel = "prf_flower_level"

// PrfFlowerLevel mapped from table <prf_flower_level>
type PrfFlowerLevel struct {
	ID           int32  `gorm:"column:id;type:int;primaryKey" json:"id"`
	Flower       int32  `gorm:"column:flower;type:int;uniqueIndex:fl,priority:1;index:idx_fl_cover,priority:1;comment:花id" json:"flower"` // 花id
	Level        int32  `gorm:"column:level;type:int;uniqueIndex:fl,priority:2;index:idx_fl_cover,priority:2;comment:花-等级" json:"level"`  // 花-等级
	SeedUp       int32  `gorm:"column:seed_up;type:int;comment:升到下级需要的种子，最大等级填-1" json:"seed_up"`                                         // 升到下级需要的种子，最大等级填-1
	CoinUp       int32  `gorm:"column:coin_up;type:int;comment:升到下级需要的金币，最大等级填-1" json:"coin_up"`                                         // 升到下级需要的金币，最大等级填-1
	ReapExp      int32  `gorm:"column:reap_exp;type:int;comment:收割经验" json:"reap_exp"`                                                    // 收割经验
	ReapRound    int32  `gorm:"column:reap_round;type:int;comment:收获次数" json:"reap_round"`                                                // 收获次数
	ReapInterval int32  `gorm:"column:reap_interval;type:int;comment:收获间隔" json:"reap_interval"`                                          // 收获间隔
	SeedDrop     int32  `gorm:"column:seed_drop;type:int;comment:种子掉落数量" json:"seed_drop"`                                                // 种子掉落数量
	SeedDropRate string `gorm:"column:seed_drop_rate;type:varchar(255);comment:种子掉落概率，填100代表1%概率" json:"seed_drop_rate"`                  // 种子掉落概率，填100代表1%概率
	ReapCnt      int32  `gorm:"column:reap_cnt;type:int;index:idx_fl_cover,priority:3;comment:一次收获几个" json:"reap_cnt"`                    // 一次收获几个
	FlowerMin    int32  `gorm:"column:flower_min;type:int;index:idx_fl_cover,priority:4;comment:摘花保底数量" json:"flower_min"`                // 摘花保底数量
}

// TableName PrfFlowerLevel's table name
func (*PrfFlowerLevel) TableName() string {
	return TableNamePrfFlowerLevel
}
