// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysGm = "sys_gm"

// SysGm gm用户
type SysGm struct {
	UID  int64     `gorm:"column:uid;type:bigint;primaryKey" json:"uid"`
	Tips string    `gorm:"column:tips;type:varchar(64)" json:"tips"`
	Time time.Time `gorm:"column:time;type:timestamp;default:CURRENT_TIMESTAMP" json:"time"`
}

// TableName SysGm's table name
func (*SysGm) TableName() string {
	return TableNameSysGm
}
