// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	UID      int64     `gorm:"column:uid;type:bigint;primaryKey" json:"uid"`
	Platform string    `gorm:"column:platform;type:varchar(32);not null;index:idx_platform_openid,priority:1" json:"platform"`
	Openid   string    `gorm:"column:openid;type:varchar(64);not null;index:idx_openid,priority:1;index:idx_platform_openid,priority:2" json:"openid"`
	Sid      int32     `gorm:"column:sid;type:int unsigned;not null;index:idx_sid,priority:1" json:"sid"`
	Name     string    `gorm:"column:name;type:varchar(64)" json:"name"`
	Head     string    `gorm:"column:head;type:varchar(256)" json:"head"`
	Born     time.Time `gorm:"column:born;type:datetime;not null;index:idx_born,priority:1;default:CURRENT_TIMESTAMP" json:"born"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
