// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserItem = "user_item"

// UserItem mapped from table <user_item>
type UserItem struct {
	UID int64 `gorm:"column:uid;type:bigint;primaryKey" json:"uid"`
	Tid int32 `gorm:"column:tid;type:int;primaryKey" json:"tid"`
	Cnt int32 `gorm:"column:cnt;type:int" json:"cnt"`
}

// TableName UserItem's table name
func (*UserItem) TableName() string {
	return TableNameUserItem
}
