// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserData = "user_data"

// UserData mapped from table <user_data>
type UserData struct {
	UID   int32  `gorm:"column:uid;type:int;primaryKey;index:idx_uid,priority:1" json:"uid"`
	Key   string `gorm:"column:key;type:varchar(128);primaryKey" json:"key"`
	Value string `gorm:"column:value;type:text" json:"value"`
}

// TableName UserData's table name
func (*UserData) TableName() string {
	return TableNameUserData
}
