// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserTask = "user_task"

// UserTask mapped from table <user_task>
type UserTask struct {
	UID    int64 `gorm:"column:uid;type:bigint;primaryKey;index:idx_uid_taskid_addtm_done,priority:1" json:"uid"`
	Taskid int32 `gorm:"column:taskid;type:int;primaryKey;index:idx_uid_taskid_addtm_done,priority:2" json:"taskid"`
	Addtm  int32 `gorm:"column:addtm;type:int;index:idx_uid_taskid_addtm_done,priority:3;comment:添加时间" json:"addtm"`   // 添加时间
	Done   int32 `gorm:"column:done;type:tinyint;index:idx_uid_taskid_addtm_done,priority:4;comment:是否完成" json:"done"` // 是否完成
	Donetm int32 `gorm:"column:donetm;type:int;comment:完成时间" json:"donetm"`                                            // 完成时间
}

// TableName UserTask's table name
func (*UserTask) TableName() string {
	return TableNameUserTask
}
