apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-go
  labels:
    app: server-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-go
  template:
    metadata:
      labels:
        app: server-go
    spec:
      containers:
        - name: main
          image: server-go
          imagePullPolicy: Always
          ports:
            - containerPort: 7001
