// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server_go/internal/dao/internal"
)

// LogLoginDao is the data access object for the table _log_login.
// You can define custom methods on it to extend its functionality as needed.
type LogLoginDao struct {
	*internal.LogLoginDao
}

var (
	// LogLogin is a globally accessible object for table _log_login operations.
	LogLogin = LogLoginDao{internal.NewLogLoginDao()}
)

// Add your custom methods and functionality below.
