// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server_go/internal/dao/internal"
)

// logMsgDao is the data access object for the table log_msg.
// You can define custom methods on it to extend its functionality as needed.
type logMsgDao struct {
	*internal.LogMsgDao
}

var (
	// LogMsg is a globally accessible object for table log_msg operations.
	LogMsg = logMsgDao{internal.NewLogMsgDao()}
)

// Add your custom methods and functionality below.
