// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server_go/internal/dao/internal"
)

// LogMsgDao 是表 _log_msg 的数据访问对象。
// You can define custom methods on it to extend its functionality as needed.
type LogMsgDao struct {
	*internal.LogMsgDao
}

var (
	// LogMsg is a globally accessible object for table _log_msg operations.
	LogMsg = LogMsgDao{internal.NewLogMsgDao()}
)

// Add your custom methods and functionality below.
