// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server_go/internal/dao/internal"
)

// LogTraceDao is the data access object for the table _log_trace.
// You can define custom methods on it to extend its functionality as needed.
type LogTraceDao struct {
	*internal.LogTraceDao
}

var (
	// LogTrace is a globally accessible object for table _log_trace operations.
	LogTrace = LogTraceDao{internal.NewLogTraceDao()}
)

// Add your custom methods and functionality below.
