// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server_go/internal/dao/internal"
)

// logLoginDao is the data access object for the table log_login.
// You can define custom methods on it to extend its functionality as needed.
type logLoginDao struct {
	*internal.LogLoginDao
}

var (
	// LogLogin is a globally accessible object for table log_login operations.
	LogLogin = logLoginDao{internal.NewLogLoginDao()}
)

// Add your custom methods and functionality below.
