// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server_go/internal/dao/internal"
)

// logTraceDao is the data access object for the table log_trace.
// You can define custom methods on it to extend its functionality as needed.
type logTraceDao struct {
	*internal.LogTraceDao
}

var (
	// LogTrace is a globally accessible object for table log_trace operations.
	LogTrace = logTraceDao{internal.NewLogTraceDao()}
)

// Add your custom methods and functionality below.
