// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server_go/internal/dao/internal"
)

// memConfigDao is the data access object for the table mem_config.
// You can define custom methods on it to extend its functionality as needed.
type memConfigDao struct {
	*internal.MemConfigDao
}

var (
	// MemConfig is a globally accessible object for table mem_config operations.
	MemConfig = memConfigDao{internal.NewMemConfigDao()}
)

// Add your custom methods and functionality below.
