// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server_go/internal/dao/internal"
)

// prfResDao is the data access object for the table prf_res.
// You can define custom methods on it to extend its functionality as needed.
type prfResDao struct {
	*internal.PrfResDao
}

var (
	// PrfRes is a globally accessible object for table prf_res operations.
	PrfRes = prfResDao{internal.NewPrfResDao()}
)

// Add your custom methods and functionality below.
