// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server_go/internal/dao/internal"
)

// prfFlowerLevelDao is the data access object for the table prf_flower_level.
// You can define custom methods on it to extend its functionality as needed.
type prfFlowerLevelDao struct {
	*internal.PrfFlowerLevelDao
}

var (
	// PrfFlowerLevel is a globally accessible object for table prf_flower_level operations.
	PrfFlowerLevel = prfFlowerLevelDao{internal.NewPrfFlowerLevelDao()}
)

// Add your custom methods and functionality below.
