// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server_go/internal/dao/internal"
)

// prfFlowerDao is the data access object for the table prf_flower.
// You can define custom methods on it to extend its functionality as needed.
type prfFlowerDao struct {
	*internal.PrfFlowerDao
}

var (
	// PrfFlower is a globally accessible object for table prf_flower operations.
	PrfFlower = prfFlowerDao{internal.NewPrfFlowerDao()}
)

// Add your custom methods and functionality below.
