// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server_go/internal/dao/internal"
)

// prfTaskDao 是表 prf_task 的数据访问对象。
// You can define custom methods on it to extend its functionality as needed.
type prfTaskDao struct {
	*internal.PrfTaskDao
}

var (
	// PrfTask is a globally accessible object for table prf_task operations.
	PrfTask = prfTaskDao{internal.NewPrfTaskDao()}
)

// Add your custom methods and functionality below.
