// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server_go/internal/dao/internal"
)

// prfItemDao is the data access object for the table prf_item.
// You can define custom methods on it to extend its functionality as needed.
type prfItemDao struct {
	*internal.PrfItemDao
}

var (
	// PrfItem is a globally accessible object for table prf_item operations.
	PrfItem = prfItemDao{internal.NewPrfItemDao()}
)

// Add your custom methods and functionality below.
