// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server_go/internal/dao/internal"
)

// sysDieDao is the data access object for the table sys_die.
// You can define custom methods on it to extend its functionality as needed.
type sysDieDao struct {
	*internal.SysDieDao
}

var (
	// SysDie is a globally accessible object for table sys_die operations.
	SysDie = sysDieDao{internal.NewSysDieDao()}
)

// Add your custom methods and functionality below.
