// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server_go/internal/dao/internal"
)

// sysGmDao is the data access object for the table sys_gm.
// You can define custom methods on it to extend its functionality as needed.
type sysGmDao struct {
	*internal.SysGmDao
}

var (
	// SysGm is a globally accessible object for table sys_gm operations.
	SysGm = sysGmDao{internal.NewSysGmDao()}
)

// Add your custom methods and functionality below.
