// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server_go/internal/dao/internal"
)

// userBagDao 是表 user_bag 的数据访问对象。
// You can define custom methods on it to extend its functionality as needed.
type userBagDao struct {
	*internal.UserBagDao
}

var (
	// UserBag is a globally accessible object for table user_bag operations.
	UserBag = userBagDao{internal.NewUserBagDao()}
)

// Add your custom methods and functionality below.
