// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server_go/internal/dao/internal"
)

// userBagTpDao 是表 user_bag_tp 的数据访问对象。
// You can define custom methods on it to extend its functionality as needed.
type userBagTpDao struct {
	*internal.UserBagTpDao
}

var (
	// UserBagTp is a globally accessible object for table user_bag_tp operations.
	UserBagTp = userBagTpDao{internal.NewUserBagTpDao()}
)

// Add your custom methods and functionality below.
