// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server_go/internal/dao/internal"
)

// userLoginkeyDao is the data access object for the table user_loginkey.
// You can define custom methods on it to extend its functionality as needed.
type userLoginkeyDao struct {
	*internal.UserLoginkeyDao
}

var (
	// UserLoginkey is a globally accessible object for table user_loginkey operations.
	UserLoginkey = userLoginkeyDao{internal.NewUserLoginkeyDao()}
)

// Add your custom methods and functionality below.
