// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server_go/internal/dao/internal"
)

// userOnlineDao is the data access object for the table user_online.
// You can define custom methods on it to extend its functionality as needed.
type userOnlineDao struct {
	*internal.UserOnlineDao
}

var (
	// UserOnline is a globally accessible object for table user_online operations.
	UserOnline = userOnlineDao{internal.NewUserOnlineDao()}
)

// Add your custom methods and functionality below.
