// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server_go/internal/dao/internal"
)

// userDataDao 是表 user_data 的数据访问对象。
// You can define custom methods on it to extend its functionality as needed.
type userDataDao struct {
	*internal.UserDataDao
}

var (
	// UserData is a globally accessible object for table user_data operations.
	UserData = userDataDao{internal.NewUserDataDao()}
)

// Add your custom methods and functionality below.
