// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server_go/internal/dao/internal"
)

// userResDao 是表 user_res 的数据访问对象。
// You can define custom methods on it to extend its functionality as needed.
type userResDao struct {
	*internal.UserResDao
}

var (
	// UserRes is a globally accessible object for table user_res operations.
	UserRes = userResDao{internal.NewUserResDao()}
)

// Add your custom methods and functionality below.
