// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server_go/internal/dao/internal"
)

// userTaskDao is the data access object for the table user_task.
// You can define custom methods on it to extend its functionality as needed.
type userTaskDao struct {
	*internal.UserTaskDao
}

var (
	// UserTask is a globally accessible object for table user_task operations.
	UserTask = userTaskDao{internal.NewUserTaskDao()}
)

// Add your custom methods and functionality below.
