// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server_go/internal/dao/internal"
)

// userItemDao is the data access object for the table user_item.
// You can define custom methods on it to extend its functionality as needed.
type userItemDao struct {
	*internal.UserItemDao
}

var (
	// UserItem is a globally accessible object for table user_item operations.
	UserItem = userItemDao{internal.NewUserItemDao()}
)

// Add your custom methods and functionality below.
