// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server_go/internal/dao/internal"
)

// userLoginkeyDao 是表 user_loginkey 的数据访问对象。
// You can define custom methods on it to extend its functionality as needed.
type userLoginkeyDao struct {
	*internal.UserLoginkeyDao
}

var (
	// UserLoginkey is a globally accessible object for table user_loginkey operations.
	UserLoginkey = userLoginkeyDao{internal.NewUserLoginkeyDao()}
)

// Add your custom methods and functionality below.
