// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package control

import (
	"server_go/api/control"
)

type ControllerV1 struct{}

func NewV1() control.IControlV1 {
	return &ControllerV1{}
}
