// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package health

import (
	"server_go/api/health"
)

type ControllerV1 struct{}

func NewV1() health.IHealthV1 {
	return &ControllerV1{}
}
