// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package grid

import (
	"server_go/api/grid"
)

type ControllerV1 struct{}

func NewV1() grid.IGridV1 {
	return &ControllerV1{}
}
